### ISSUE TITLE
OS user during ssh command

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardenctl#108]
Currently the ssh command outputs always user `core`. 
With the support of new operating systems like Ubuntu and JeOS, the `core` user is no longer valid and available.
For Ubuntu the user is `ubuntu`, for JeOS - `ec2-user`.

**Comment by KristianZH** [comment]
As a short-term solution i can just change the connect message to:

```Connect: ssh -i key -o "ProxyCommand ssh -W %h:%p -i key <username>@34.254.230.86" <username>@10.242.11.39```
And maybe a message which says to look on the cloud provider documentation and find the user for their OS there.

@ialidzhikov @DockToFuture 
What do you think about this?

**Comment by ialidzhikov** [comment]
IMO it is okay for temp solution.

**Comment by DockToFuture** [comment]
After making use of the provisioned ```gardener``` user, can we close this?
@ialidzhikov @KristianZH

**Comment by KristianZH** [comment]
I think that we use it only for the bastions for now

**Comment by KristianZH** [comment]
I am currently working now on PR, where the ssh command will work with `node-name`, not `ip`.

In this way the `node-name` would be taken from the machine object and we would be able to ssh even on not joined node in the cluster. After that i will fix this issue and will close it :)

**Comment by KristianZH** [comment]
Yes, i think we can close it :)
