### ISSUE TITLE
Targeting shoots may take long

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardenctl#127]
**Describe the bug**
On large landscapes with many shoots, `gardenctl target shoot` may take very long.

**To Reproduce**
See above.

**Expected behavior**
The command should finish within a second or so.

**Gardenctl Version (please complete the following information):**
```
$ g version
gardenctl:
	version     : 0.11.0
	build date  : 2019-06-14
	go version  : go1.12.5
	go compiler : gc
	platform    : darwin/amd64
```

**Comment by ialidzhikov** [comment]
+1
