### ISSUE TITLE
Gardenctl cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl#142]
**Describe the bug**
When I try to run `gardenctl` I see the following error message:
`"gardenctl" cannot be opened because the developer cannot be verified.`

**To Reproduce**
1. Use macOS 10.15.1
2. Download latest gardenctl (the issue probably occurs with every gardenctl version I assume)
3. Just run gardenctl with `gardenctl`

**Expected behavior**
I should be able to run `gardenctl` without errors

**Screenshots**
<img width="444" alt="Screenshot 2019-11-13 at 13 22 40" src="https://user-images.githubusercontent.com/5526658/68763530-f5bce300-0618-11ea-80bb-3daa9c4bbbfb.png">

**Gardenctl Version (please complete the following information):**
 - Version 0.14.0

**Additional context**
It's probably related to macOS Catalina (version 10.15.x)

**Comment by petersutter** [comment]
I was able to workaround it by 
- navigating to the `gardenctl` bin in the `finder`
- right click on the `gardenctl` bin -> Open (and holding the shift key)
- confirm the dialog by pressing the `Open` button.

**Comment by DockToFuture** [comment]
In the past you could select under Security Preferences:
Allow downloaded Apps from ```Anywhere```.
Catalina only allows ```App store ``` and ```App store & identified developer```
In order to become one you have  to join Apple's Developer Program for $99 per year.

**Comment by DockToFuture** [comment]
But you could bypass gatekeeper with sudo ```spctl --master-disable``` which will set the ```Anywhere``` option again.

**Comment by ialidzhikov** [comment]
Also this happens only when you download the binary via the browser. You should use the README.md install instructions where curl is used - ref https://github.com/gardener/gardenctl/tree/v0.15.0#installation.

Ref https://github.com/bazelbuild/bazel/issues/9304#issuecomment-527936336.

/close
