### ISSUE TITLE
Multiple gardenctl command arguments

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl#143]
Currently, you have to run multiple commands in order to target a shoot for a specific garden 
 landscape and project.
`gardenctl target garden my-garden`
`gardenctl target project my-project`
`gardenctl target shoot my-shoot`

Allow gardenctl to be called with multiple arguments. Something like:
`gardenctl target --garden my-garden --project my-project --shoot my-shoot`

**Comment by rfranzke** [comment]
+1, very much appreciated. IMHO it would be even better if it would be possible to omit the `--<flag>` flags, i.e., `gardenctl target my-garden my-project my-shoot`

**Comment by petersutter** [comment]
and instead of running the following commands for all landscapes:
`gardenctl target garden dev`
`gardenctl register`
`gardenctl target garden staging`
`gardenctl register`
`gardenctl target garden canary`
`gardenctl register`
....

this should be possible:

- `gardenctl register dev staging canary`
- `gardenctl unregister dev staging canary`

optimally this does not change the current target

**Comment by DockToFuture** [comment]
``` g register  --all```
