### ISSUE TITLE
gardenctl gets wrong Shoot credentials

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardenctl#147]
**Describe the bug**

**To Reproduce**
1. Find a Shoot name that is used several times across multiple  projects - e.g dev
2. Execute a cloud provider specific command like `g aws ec2 describe-instances`
3. Ensure that the instances could be from different account and credentials under `~/.garden/cache/<landscape>/projects/<proj>/<shoot>/.aws/credentials` are different from the Shoot one.

**Expected behavior**

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - Version/Commit [e.g. b21b4bde14663faee381697cb1d93a8b53a3e81a]

**Additional context**

**Comment by jfortin-sap** [comment]
@DockToFuture I can take this one
