### ISSUE TITLE
gardenctl register <email> does not work

### ISSUE THREAD

**Issue by JensHaley** [gardener/gardenctl#159]
**Describe the bug**
gardenctl register <mail> does not work. It worked with kubectl.

Response after executing command (slightly modified for security reasons):
```
$ gardenctl register mymail@mydomain
Format Validated
secrets "virtual-garden-xxx-yyy-zzz" not found
```

**To Reproduce**
1. Which target was set 'gardenctl get target'
Contact me for details.

2. Which command was entered [e.g. 'gardenctl show vpn-seed']
See above.
3. What was the output of the command 
See above.

**Expected behavior**
Same output as when using the kubectl client to do the same thing.

**Screenshots**

**Gardenctl Version (please complete the following information):**
```
gardenctl:
		version     : v0.15.0
		build date  : 2019-12-10
		go version  : go1.13.4
		go compiler : gc
		platform    : linux/amd64
```

**Additional context**

**Comment by petersutter** [comment]
Hi @JensHaley, please update your gardenctl to v0.16.0

**Comment by DockToFuture** [comment]
The domain has altered therefore please update to the latest version.

**Comment by JensHaley** [comment]
Thanks. That helped.
