### ISSUE TITLE
Inform in case newer version is available

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl#160]
It would be nice if gardenctl would inform me if a new version is available, similar like other tools do it. And maybe also give instructions on how to update.

**Comment by neo-liang-sap** [comment]
the latest release version could be obtained via (i took shell for example)
```
curl --silent "https://api.github.com/repos/gardener/gardenctl/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
```
returns `v0.16.0`

i will investigate how to implement sth similar in go for `gardenctl`.

please assign this ticket to me, thanks!
