### ISSUE TITLE
SSH private key file saved in current directory when using `gardenctl ssh`

### ISSUE THREAD

**Issue by plkokanov** [gardener/gardenctl#161]
Currently when using `gardenctl ssh` the private key is saved in the current directory (from where the command is called), at least when ssh-ing to aws nodes. If someone forgets to delete the key immediately after the session is over, or some other action is done on the current dir - it is copied, archived, commited in git we risk exposing credential

For alicloud I see that the key is moved to the gardenctl cache dir after it is downloaded (however, I haven't checked how it is handled for other IaaSes). We should do that for all providers (better solution might be to use the ~/.ssh directory). 

Generally it would be perfect if we could keep the key only in memory temporarily but I'm not sure if that will be possible.

**Comment by vpnachev** [comment]
> We should do that for all providers (better solution might be to use the ~/.ssh directory

I think it is better to keep it next to the kubeconfig file of the same shoot cluster in `${HOME}/.garden/cache`.

**Comment by neo-liang-sap** [comment]
Hello,

I'm trying to make some contribution to `gardenctl` :)

Here's the PR - https://github.com/gardener/gardenctl/pull/166

BTW please assign this ticket to me - i don't have access to self-assign...

Thanks!
-Neo
