### ISSUE TITLE
Install link not working?

### ISSUE THREAD

**Issue by WorkAlexGahr** [gardener/gardenctl#162]
Hi,

seem when i use 

curl -LO https://github.com/gardener/gardenctl/releases/download/$\(curl -s https://raw.githubusercontent.com/gardener/gardenctl/master/LATEST\)/gardenctl-darwin-amd64

I get 

404: Not Found

Ist the link still correct?

**Comment by DockToFuture** [comment]
Try `curl -LO https://github.com/gardener/gardenctl/releases/download/$(curl -s https://raw.githubusercontent.com/gardener/gardenctl/master/LATEST)/gardenctl-darwin-amd64`

For some reason you have two `\` in your link.

**Comment by WorkAlexGahr** [comment]
Thanks i think still not working:

Ok even on webbrowser i get :https://raw.githubusercontent.com/gardener/gardenctl/master/LATEST/gardenctl-darwin-amd64

gets a 404

**Comment by DockToFuture** [comment]
It can't work in the webbrowser with this url, the inner part is just used to fetch the version in this case `v0.16.0`. Either you use `https://github.com/gardener/gardenctl/releases/download/v0.16.0/gardenctl-darwin-amd64` or use `curl -LO https://github.com/gardener/gardenctl/releases/download/$(curl -s https://raw.githubusercontent.com/gardener/gardenctl/master/LATEST)/gardenctl-darwin-amd64`.

**Comment by WorkAlexGahr** [comment]
boot give me booth a 404 not found 
I'm using zsh on the mac any issue with this?

**Comment by petersutter** [comment]
I have the same issue with zsh. When copying the text, it will automatically add `\` before `(` and `)`

**Comment by DockToFuture** [comment]
If this is a zsh autoplugin problem use `bash` and then download gardenctl.
