### ISSUE TITLE
Target garden by apiServerUrl

### ISSUE THREAD

**Issue by petersutter** [gardener/gardenctl#164]
It would be nice if I could target the `garden` by providing the `apiServerUrl` / `server` as alternative to the name.

Background: In the dashboard on the cluster's details page an operator should be able to copy the `gardenctl` commands to
- target the shoot
  - Example:`gardenctl target --server https://example.com --seed the-seed --shoot my-shoot`) 
- target the seed of this shoot
  - Example: `gardenctl target --server https://example.com --seed the-seed`)

As the name of the garden varies for each local setup this could be way to uniquely identify the garden.

This could save some time typing and targeting the correct garden, shoot / seed.

In order for `gardenctl` to find the correct garden, it should check the `server` field in the kubeconfigs referenced in the respective gardens that matches the value of the `server` parameter. 
If either the kubeconfig or the `server` parameter is an ip and the other one a hostname, it first has to do a nslookup before comparison, of course.

**Comment by petersutter** [comment]
with https://github.com/gardener/gardenctl/issues/165 one could also target the namespace in addition, like `gardenctl target --server https://example.com --seed the-seed --namespace shoot-technical-id`

**Comment by neo-liang-sap** [comment]
some internal discussion with @petersutter ;)
