### ISSUE TITLE
enable `gardenctl` to support select namespace while targeting garden/seed/shoot

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#165]
Currently with 0.16 version of `gardenctl` we can target sth like `gardenctl target -g <GARDEN> -s <SEED> -t <SHOOT>`
It would be nice to add an switch of `-n namespace` to select the namespace

**Comment by neo-liang-sap** [comment]
Oh - looks like i can't assign this issue to myself ;) could someone assign this to me? or add me permission in this repo to take issues ;)
my username is `neo-liang-sap`
Thanks!

**Comment by petersutter** [comment]
done

**Comment by neo-liang-sap** [comment]
Hi @petersutter :

I looked into `gardenctl target` related code and have some thoughts on this issue, do correct me if i was wrong in understanding this issue.

Currently there are 4 kinds of `target` - garden/seed/project/shoot - see https://github.com/gardener/gardenctl/blob/master/pkg/cmd/types.go#L73 , `namespace` is not an kind of `target`

Talking about `namespace` personally i think this should be kind of native concept in `kubectl`, it is meaningful to switch `namespace` while performing `kubectl` action, just like we switch `garden target` while performing `gardenctl` action

I see there's already an `kn` implementation for `kubectl` to switch namespace in https://github.com/gardener/gardenctl/blob/master/pkg/cmd/kubectl.go#L76 - which equals `kubectl --namespace=xxx`

* Do we still need to implement `gardenctl target -n namespace` as `gardenctl kn` already implemented this?

* If needed, what will be the desired outcome result if we implement `gardenctl target -n namespace`? 
Now in my debugging of shoot i use
1) `gardenctl target -g xxx -s xxx`
2) `kubectl` to switch namespace to `shoot_techinical_id`
So the desired implementation is 
`gardenctl target -g xxx -s xxx -n namespace` = 1) + 2)?

Do correct me if i was in wrong understanding of these above...Thanks!

cc @dansible

**Comment by petersutter** [comment]
> * Do we still need to implement `gardenctl target -n namespace` as `gardenctl kn` already implemented this?

The problem with this is that you can't combine it into one command, so I guess your second point is desired outcome, if possible.

So from my point of view, when running
`gardenctl target -g xxx -s xxx -n namespace`
and then
`gardenctl k get pods` it would list the pods of the targeted namespace

**Comment by neo-liang-sap** [comment]
PR - https://github.com/gardener/gardenctl/pull/168
