### ISSUE TITLE
Type in dialogue

### ISSUE THREAD

**Issue by ThormaehlenFred** [gardener/gardenctl#174]
**Describe the bug**
When executing gardenctl ssh, there is a small typo in the dialogue
current
`Opend SSH Port on Node.`

**To Reproduce**
gardenctl ssh

**Expected behavior**
should be: 
`Opened SSH port on node.`

**Screenshots**
```
(2/4) Setting up bastion host security group
Bastion host security group set up.
Opend SSH Port on Node.
```

**Gardenctl Version (please complete the following information):**
 - latest

**Additional context**

**Comment by DockToFuture** [comment]
Is fixed.
