### ISSUE TITLE
Not possible to use OIDC based kubeconfig files for authentication 

### ISSUE THREAD

**Issue by donistz** [gardener/gardenctl#175]
**Describe the bug**
It is not possible to use gardenctl for operation of seed clusters where the K8S API Server is configured with OIDC based authentication. 
**Expected behavior**
It should be possible to configure the usage of OIDC based kubeconfig files for accessing the Gardener seed clusters.

**Comment by vpnachev** [comment]
There is an issue in gardener about generating kubeconfig with OIDC context - https://github.com/gardener/gardener/issues/1433. It should ease support in gardenctl about OIDC.

**Comment by neo-liang-sap** [comment]
Hi @DockToFuture / @vpnachev 
Currently in oidc enabled scenario, `gardenctl` is not able to target `shoot`, i'm not sure whether i'm using correctly as follows, will this issue https://github.com/gardener/gardenctl/issues/175 fix this? or https://github.com/gardener/gardener/issues/1433 will fix?
CC @dansible 
Thanks!

![image](https://user-images.githubusercontent.com/42594392/85349733-d3396380-b531-11ea-8c0b-d87e6e231d01.png)

**Comment by neo-liang-sap** [comment]
@DockToFuture as https://github.com/gardener/gardenctl/pull/221 is closed and merged i believe this one could also be closed?
thanks
-Neo

**Comment by DockToFuture** [comment]
Thanks for noticing. Closed with #221.
