### ISSUE TITLE
Faster way to target Shoots

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardenctl#18]
Is there a faster way to target a Shoot cluster other than
```yaml
$ gardenctl target project <NAME>
$ gardenctl target shoot <NAME>
```
?

If not, can we have a faster way to do so?

Thanks.

**Comment by DockToFuture** [comment]
A faster way is `gardenctl target <NAME>`

**Comment by rfranzke** [comment]
Just tried that out:

```
$ gardenctl ls projects
[...]
- project: hugo
  shoots:
  - foobar
[...]

$ gardenctl target foobar
No match for foobar
```

**Comment by rfranzke** [comment]
We identified that the current target stack must directly point to the Garden cluster, otherwise it won't work. `gardenctl get target` shows the current target stack (help text is misleading and going to be improved), `gardenctl drop` drops a target from the stack.

Closing the ticket therefore.
