### ISSUE TITLE
gardenctl target target -u

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardenctl#188]
Can we support targeting a cluster by providing the Gardener Dashboard URL?
For example:

```bash
gardenctl target -u https://<url-to-dashboard>/namespace/garden-project/shoots/my-shoot/
```

**Comment by neo-liang-sap** [comment]
sure i will look into it, please assign this issue to me , thanks!

**Comment by rfranzke** [comment]
Thanks Neo!

**Comment by neo-liang-sap** [comment]
PR submitted in https://github.com/gardener/gardenctl/pull/190
