### ISSUE TITLE
Gardenctl fails for AWS -  hardcoded instance type

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardenctl#193]
**Describe the bug**
Currently for AWS the instance-type t2 is hardcoded when [creating the bastion instance](https://github.com/gardener/gardenctl/blob/10a537942b94234914758c0f6d053dc1cf218ecd/pkg/cmd/ssh_aws.go#L236).

Depending on the AWS region, the [T2 instance type is unavailable](https://github.com/trailofbits/algo/issues/1285 ) and leads the following error. 
It was not immediately clear to me that this is the raw error from the awscli: 

```
(3/4) Creating bastion host

An error occurred (Unsupported) when calling the RunInstances operation: The requested configuration is currently not supported. Please check the documentation for supported configurations.
```

**To Reproduce**
Execute gardenctl ssh <node> for a node in the AWS region **eu-north-1**

**Expected behavior**

Gardenctl should check that the T2 instance type is available in the given region of the node.
If not it should  either
 - return an error stating the available instance types & lets the user pick one.
- pick an available instance type

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - Version/Commit [e.g. b21b4bde14663faee381697cb1d93a8b53a3e81a]

**Additional context**

**Comment by neo-liang-sap** [comment]
please assign this issue to me, thanks
