### ISSUE TITLE
Automatically export the targeted kubeconfig

### ISSUE THREAD

**Issue by jfortin-sap** [gardener/gardenctl#197]
**What would you like to be added:**
Automatically export the targeted kubeconfig and load it in the environment (KUBECONFIG)

**Why is this needed:**
Facilitate switching between multiple clusters without specifying gardenctl

**Comment by danielfoehrKn** [comment]
Environment variables can only be passed from parent to child (as part of environment export/inheritance), not the other way around - please [see here](https://unix.stackexchange.com/questions/372627/is-it-possible-to-pass-environment-variables-from-child-to-parent-in-user-space).

I am working around this issue in the [tool I am using](https://github.com/danielfoehrKn/kubectl-switch), by sourcing a tiny bash script that calls the actual binary.

Though I would like too see this feature in `gardenctl`, I am unsure how to achieve this without having an additional & quite ugly bash helper script.

In the long run, I would like to have a fuzzy style search integrated in `gardenctl` for the Garden, Shoot & Seed `kubeconfigs` in a Gardener installation, similarly to the tool mentioned above.

**Comment by jfortin-sap** [comment]
@danielfoehrKn Would it be possible to create a tmp file to store the env-var, and if that tmp file exist after gardenctl exits the sub shell, then set it?

**Comment by danielfoehrKn** [comment]
Only the current shell session,  or its parent can set an environment variable that persist in the current session to my understanding.  

So you would need something that is sourced by the shell that calls gardenctl. Now gardenctl can either directly return the path to the kubeconfig file or write a tmp file somewhere, it does not really matter. Then the caller can consume that and set it as en environment variable.

Possibly there is another solution out there that I have not thought of :)

**Comment by jfortin-sap** [comment]
@danielfoehrKn During gardenctl execution, does it not return to parent once the command is complete? and then before it exits we can perform an operation?

**Comment by danielfoehrKn** [comment]
If you execute the `gardenctl` binary from the command line it will [fork()](https://man7.org/linux/man-pages/man2/fork.2.html)  the current shell process and then exec() into the child process. `gardenctl` therefore runs in a child process. So you cannot just set the environment variable in `gardenctl` before it exits.
