### ISSUE TITLE
Index out of bounds if config is empty

### ISSUE THREAD

**Issue by grolu** [gardener/gardenctl#20]
This is a minor issue that I noticed when I first installed gardenctl on my Mac. After building the tool, I typed
`gardenctl`
and got the following error message
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gardener/gardenctl/cmd.getGardenClusterKubeConfigFromConfig()
	/Users/d047401/go/src/github.com/gardener/gardenctl/cmd/miscellaneous.go:47 +0x359
github.com/gardener/gardenctl/cmd.Execute()
	/Users/d047401/go/src/github.com/gardener/gardenctl/cmd/root.go:62 +0x508
main.main()
	/Users/d047401/go/src/github.com/gardener/gardenctl/gardenctl.go:20 +0x20
```
The reason for the error is that I was lacking a cluster entry in the gardenctl config file.
However, I would expect some nicer output, something like "You need to add a cluster config to your configuration before you can use the tool" rather than an out of bounds exception.

**Comment by DockToFuture** [comment]
Thank you for reporting this issue, exception handling was added and issue is therefore closed.
