### ISSUE TITLE
Not possible to SSH to a node 

### ISSUE THREAD

**Issue by jguipi** [gardener/gardenctl#216]
**Describe the bug**

While trying to troubleshoot a cluster that was generating the following error :
```
Failed while waiting for all machine deployments to be ready: 'machine shoot--zz-zzz--zzzzzzzzz-zzzz-zzzz-zz-zzzzzzzzzz-zzzzz failed: Machine shoot--zz-zzz--zzzzzzzzz-zzzz-zzzz-zz-zzzzzzzzzz-zzzzz failed to join the cluster in 20m0s minutes.'
```
I noticed that I wasn't able to ssh to the node using `gardenctl ssh` it always threw an error at the bastion host creation.
![image](https://user-images.githubusercontent.com/11049349/86257095-19707180-bb87-11ea-8c11-4c416d32cb6f.png)

**To Reproduce**
```gardenctl ssh <nodename>```

**Expected behavior**
The command to work

**Gardenctl Version (please complete the following information):**
![image](https://user-images.githubusercontent.com/11049349/86257175-39079a00-bb87-11ea-8ee5-c2c26f712a39.png)

**Comment by tedteng** [comment]
Hi Juste, have you try `ssh shell <nodename>`. meanwhile, I am trying to search project zz-zzz from live and canry but didn't found it do you have project dashboard URL ? I like to reproduce the issues.

**Comment by jguipi** [comment]
The cluster seems to have resolve itself
