### ISSUE TITLE
gardenctl can not support aws format kubeconfig

### ISSUE THREAD

**Issue by knightXun** [gardener/gardenctl#217]
it's seems gardenctl will read some content from kubeconfig, and judge the format whether is illeage.I see some code of gardenctl and compare this with my aws format kubeconfig, finding gardenctl can not support aws kubeconfig very well. Please notice this.

**Comment by neo-liang-sap** [comment]
gardenctl can't support some kind of kubeconfig e.g. containing use with command line content.
say if your kubeconfig user part contains `aws-iam-authenticator` command line to generate user info, this could not be consumed by gardenctl

btw i found some misunderstanding content in your description which i can't edit them, e.g. `weather `->`wether`, `finding gardenctl can support aws kubeconfig very well`->`finding gardenctl can't support aws kubeconfig very well`, correct me if i was wrong.

thanks

**Comment by knightXun** [comment]
@neo-liang-sap thanks.
