### ISSUE TITLE
How can I write right config for gardenctl?

### ISSUE THREAD

**Issue by knightXun** [gardener/gardenctl#220]
![image](https://user-images.githubusercontent.com/8334944/87275470-b54b9700-c510-11ea-8651-4876c43bde89.png)

I make gardenctl config above, but I can't get any shoots. Is there some mistake in my ~/.garden/config?

**Comment by tedteng** [comment]
can you show me ` gardenctl get target` to Displays the current target ?

**Comment by knightXun** [comment]
![pp的副本](https://user-images.githubusercontent.com/8334944/87281200-8f7cbd00-c525-11ea-9d84-6207dee3d7a9.png)

**Comment by petersutter** [comment]
from the error message above it looks like you have targeted the wrong cluster. Make sure you have targeted the (virtual) garden cluster

**Comment by knightXun** [comment]
@petersutter I got it, I should download this config from garden dashboard
