### ISSUE TITLE
Unable to create bastion due to invalid IAM Instance Profile name

### ISSUE THREAD

**Issue by vlvasilev** [gardener/gardenctl#225]
**Describe the bug**
I am trying to connect to a non joining node as per this [documentation](https://gardener.cloud/documentation/050-tutorials/content/howto/shell-to-node/). When I execute `gardenctl ssh <node-name-from-machine-status>` it fails creating bastion 
```

Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key

(1/4) Fetching data from target shoot cluster
Data fetched from target shoot cluster.

(2/4) Setting up bastion host security group
Security Group exists, skipping creation.

(3/4) Creating bastion host

An error occurred (InvalidParameterValue) when calling the RunInstances operation: Value (shoot--<project>--<shoot-name>-bastions) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
```

**To Reproduce**
The gardenctl was targeting a shoot from aws on Canary.

**Expected behavior**
To successfully connect to the non joining node

**Gardenctl Version:**
```gardenctl:
   version     : v0.18.0
   build date  : 2020-06-29
   go version  : go1.14.2
   go compiler : gc
   platform    : linux/amd64
```
**Additional context**
It happens on Gardener Canary 
Project jamestest 
Shoot kyma

**Comment by neo-liang-sap** [comment]
Hi @vlvasilev , thanks for reporting this, could you please remove `C***y` from your description as it contains sensitive information? 

i was unable to re-produce your problem as i see your shoot cluster is kind of problematic - all machines are in pending status. I'm not 100% sure but i remember `garden ssh` could not ssh to machine with pending status. I would suggest you first try reconcile your shoot to see if shoot could be normal.

![image](https://user-images.githubusercontent.com/42594392/87958453-24faec80-cae4-11ea-84a6-4695c5419f57.png)

Purely based on your error description i googled and seems it's an AWS bug which AWS IAM profile could only be utilized after 2 mins of its creation - which means usually re-try would work, see [here](https://github.com/nextflow-io/nextflow/issues/617) and [here](https://github.com/terraform-providers/terraform-provider-aws/issues/838)

If retry didn't work, i will reach out to you via email for more details

thanks

-Neo

**Comment by vlvasilev** [comment]
Dear @neo-liang-sap, 
First this is not mine cluster. As Developer On Duty I wan't to ssh on a non joining node as is described in the documentation.
The shoot is old and as you see even the new machine are 10 minutes old.
I have past link to the documentation. If gardenctl have no longer such option why it is available in the latest release.

**Comment by tedteng** [comment]
Hi @vlvasilev  The IAM profile was removed https://github.com/gardener/gardenctl/pull/218 and merged in the latest version v0.18.0. It looks like your upgrade to the latest gardenctl version but seems the terminal session not the latest gardenctl version at that time.

**Comment by DockToFuture** [comment]
Can we close this issue? @vlvasilev

**Comment by vlvasilev** [comment]
@DockToFuture yes
