### ISSUE TITLE
Bash Completion Fails

### ISSUE THREAD

**Issue by rufreakde** [gardener/gardenctl#227]
**Describe the bug**
Sourcing the bash completion results in an error:
`ERROR: /dev/fd/12:type:1080: bad option: -t`

Command I tried to use in my .zshrc:
```
if [ /usr/local/bin/gardenctl ]; then source <(gardenctl completion bash); fi
```

**To Reproduce**
1. `brew install gardener/tap/gardenctl`
2. `source <(gardenctl completion bash);`
3. see error: `/dev/fd/11:type:1080: bad option: -t`

**Expected behavior**
Source of bash completion should work

**Gardenctl Version (please complete the following information):**
```
brew info gardenctl
gardener/tap/gardenctl: stable v0.18.0
Gardenctl
https://gardener.cloud
/usr/local/Cellar/gardenctl/v0.18.0 (3 files, 33.3MB) *
  Built from source on 2020-07-21 at 13:33:41
From: https://github.com/gardener/homebrew-tap/blob/HEAD/gardenctl.rb
==> Requirements
Required: x86_64 architecture ✔
```

**Additional context**
None

**Comment by neo-liang-sap** [comment]
/assign
will take look at it

**Comment by neo-liang-sap** [comment]
Hi @rufreakde ,
I assume you are using `zsh` as i saw you were trying to source to `.zshrc`, actually if you want to source completion for `zsh` you should run `source <(gardenctl completion zsh);`, it works in my Mac with zsh

from code the implementation is https://github.com/gardener/gardenctl/blob/master/pkg/cmd/completion.go#L26 you can see difference implementation in `bash` and `zsh`

for gardenctl documentation it didn't clarify you need to run different command for `bash`/`zsh` i will update the docuementation.

Thanks for reporting this and nice catching!

-Neo

**Comment by rufreakde** [comment]
Ah should have tried this from the start!
```
if [ /usr/local/bin/gardenctl ]; then source <(gardenctl completion zsh); fi
```
Works :)
Thank you very much.
