### ISSUE TITLE
As non garden admin I am not able to target shoots

### ISSUE THREAD

**Issue by wiegandf** [gardener/gardenctl#233]
**Describe the bug**
I am not an admin in this garden but wanted to use gardenctl to manage the shoots in my project. I can target my project, but not my shoots.

**To Reproduce**
1. Which target was set 'gardenctl get target'

```
- kind: project
  name: project-xyz
```
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
`gardenctl target shoot shoot-xyz`
3. What was the output of the command 
```
shoots.core.gardener.cloud "shoot-xyz" is forbidden: User "system:serviceaccount:garden-xyz:xyz-sa" cannot list resource "shoots" in API group "core.gardener.cloud" at the cluster scope
```

**Expected behavior**
I am able to target the shoots I have admin permissions to and use e.g. gardenctl ssh for it.

**Gardenctl Version (please complete the following information):**
```
gardenctl:
		version     : v0.16.0
		build date  : 2020-01-28
		go version  : go1.13.6
		go compiler : gc
		platform    : darwin/amd64
```

**Comment by petersutter** [comment]
@DockToFuture I also requested this feature in the past but I think I haven't opened an issue for it and just asked you directly if this is possible with `gardenctl`. Would be nice to have also for the [vscode-gardener-tools](https://github.com/gardener/vscode-gardener-tools/) `gardenctl` integration

**Comment by tedteng** [comment]
HI  @petersutter @DockToFuture  to achieve the goal, Can you help me identify is related with cluster role binding somewhere or depend on that the issue https://github.com/gardener/gardener/issues/1724 Thanks.

**Comment by petersutter** [comment]
Hi @tedteng afaik gardener/gardener#1724 is not related. Also it should not be necessary for `gardenctl` to list all shoots (cluster wide) when a project is on the target stack.

**Comment by tedteng** [comment]
Hi @wiegandf Can you help me elaborate more information which make my environment more closer to your scenario. 
in `~/.garden/config`  which kubeconfig file you are using, the one from My Account page or Service Accounts from Members page? thanks.

- name: dev
  kubeConfig: ~/clusters/dev/kubeconfig.yaml
- name: prod
  kubeConfig: ~/clusters/prod/kubeconfig.yaml

**Comment by petersutter** [comment]
@tedteng it should behave the same if both have the same privileges (project admin) and ideally both scenarios should work

**Comment by tedteng** [comment]
The verify Process here, let me know if I am missing something
~/.garden/config
```
- name: ttt
   kubeConfig: ~/clusters/dev/kubeconfig.yaml (kubeconfig from SA)
```

```
g target garden ttt     
Garden:
KUBECONFIG=/Users/i333878/gardener_kubeconfig/ttt/kubeconfig

g target project i33xxx
g target shoot fywubia85d
Shoot:
KUBECONFIG=/Users/i333878/.garden/cache/ttt/projects/i333xxx/fywubia85d/kubeconfig.yaml

g k get ns                                          
NAME              STATUS   AGE
default           Active   23h
kube-node-lease   Active   23h
kube-public       Active   23h
kube-system       Active   23h
```

**Comment by tedteng** [comment]
/needs/review

**Comment by tedteng** [comment]
as confirmed with @wiegandf he can target the shoot after patch the fixing for verifying.  but new issue leak of permission for `ssh`, `log`  after target shoot.  he will open a new ticket then I will working on that later.

**Comment by tedteng** [comment]
/reviewed/do-not-merge

**Comment by wiegandf** [comment]
https://github.com/gardener/gardenctl/issues/253 for the lack of permissions to ssh into nodes in the shoot cluster + retrieving logs.

**Comment by tedteng** [comment]
@petersutter @wiegandf welcome any feedback as PR https://github.com/gardener/gardenctl/pull/263
