### ISSUE TITLE
Export a script / file that can be sourced to provide the credentials for the native clients

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#235]
Per some discussion i'm opening this issue for `Export a script / file that can be sourced to provide the credentials for the native clients `

This is for `Add feature to the Infrastructure commands`

Say currently when operating against openstack  gardener shoot, we can use `gardenctl openstack xxxx`, the desired outcome of this issue is we can generate sth like `admin.rc` via some `gardenctl openstack generate-credential(??? name to be discussed)`, and after `source admin.rc`, we can use native `openstack xxxxx` command line interface

Same will be applied for aws/azure/gcp
e.g. for aws we can generate an file containing `aws_secret_xxx` etc
for azure we can generate an file containing `service_principal_id` `client_id` `client_secret` `tenant_id` `object_id` etc
for gcp ....

**Comment by jfortin-sap** [comment]
@DockToFuture What is the command arg you propose to generate the cloud provider creds?
gardenctl dump-creds? and it will be generated based on the shoot selected?

**Comment by DockToFuture** [comment]
I would propose `gardenctl get creds`. Yes it would be based on the selected target.

**Comment by jfortin-sap** [comment]
@DockToFuture I am having second thoughts about this feature. Security wise I think it's not a good idea that we store customer shoot creds on the local filesystem. I think it would be preferable to refactor the existing feature to simply execute the cloud provider cli with the credentials passed as arguments.

**Comment by jfortin-sap** [comment]
Closing this ticket, and creating a new one to pass cloud provider creds as arguments (to avoid local fs storage)
