### ISSUE TITLE
Use Gardener libraries for interacting with Hyperscalers

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#236]
**Describe the bug**

come from with colleagues yesterday one of a topic is calling native gardener function.
one example here the native gardener already supports create VM in AWS/GCP/az/OpenStack by providers.  It will be always updated base on different purpose day by day, eg, need to follow a security policy when creating VM or other compliance as needed. So calling directly from a native gardener may keep consistency and `gardenctl` also keep updated too whatever native function changed or modify.

**Comment by tedteng** [comment]
some updates,
As manual apply yaml testing, It seems workable use MCM.  I am able to create/delete the machine.

![image](https://user-images.githubusercontent.com/42234376/89864068-e1c10480-dbdd-11ea-93ab-5b6c0299c0ca.png)


however, the create/delete security group and Public IP not handled by MCM after checking with @prashanth26 
besides, some Note provider from Prashanth

```
Creation flow would look like this in IMO.
Create new security group (open 22 port)
Create VM using MCM  + PublicIP (this setting maybe available in machineClass for few providers like AWS/GCP, else you may have to create it externally)
Delete flow
Delete public IP + VM
Delete security group

NOTE: Public IP creation is allowed on MCM for some provider machine class like AWS, GCP. But i would suggest to create & delete separately  as there is not one common interface to do it for all providers so yet.
```
will continuing

**Comment by tedteng** [comment]
Currently, we use cloud clients to create VM,  if adopt Gardener libraries whether mean it highly depends on Garden status to create VM in hyperscalers?

**Comment by dansible** [comment]
Closing in favor of smaller scope issue: https://github.com/gardener/gardenctl/issues/272
