### ISSUE TITLE
SSH unstable

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardenctl#240]
**Describe the bug**

I am unsuccessful in trying to use `gardenctl ssh` with the version from the master branch (has [latest commit included]()).

**To Reproduce**
 - on an AWS VM in region `eu-north-1` using instance type t3.xLarge

```
./gardenctl-darwin-amd64 ssh ip-10-250-17-222.eu-north-1.compute.internal

Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

Downloaded id_rsa key
Check Public IP

(1/4) Fetching data from target shoot cluster
Data fetched from target shoot cluster.

(2/4) Setting up bastion host security group
Bastion host security group set up.
Opened SSH Port on Node.

(3/4) Creating bastion host
Bastion host instance i-011b9d6c4209a78aa Initializing.

Bastion host instance running.
Waiting SSH port open on Bastion
```
The command is hanging indefinitely because the internal command is not succeeding and no timeout is configured:

```
nc  -rz -w 5 <bastion-public-ip> 22
```
 

To make it worse, when killing the process with CTRL + C ( SIGINT) - the process does not seem to have a proper signal handler installed and terminates without cleaning the resources.

**Expected behavior**

- ssh connection works
- there is a timeout for the `nc` command - why did it not work?
- the resources are being cleaned up on SIGINT

**Screenshots**

Also the bastion instance is showing this status after a while:

![image](https://user-images.githubusercontent.com/33809186/89030696-47d1a000-d331-11ea-8e68-4022a62a0bf2.png)

**Gardenctl Version (please complete the following information):**
 - Version/Commit [7e7d8ba7666acce5360396907c29b251a5c33b51]

**Additional context**
Tried it multiple times today and it did not work.

**Comment by dansible** [comment]
Hi @danielfoehrKn it appears this issue has already been fixed in this PR: https://github.com/gardener/gardenctl/pull/239

Are you still having issues?

**Comment by tedteng** [comment]
Thanks for the feedback @danielfoehrKn  I will take a look. The ssh service in AWS EC2 sometimes as "BlackBox" the behavior unpredictable
