### ISSUE TITLE
[Security] Access cloud provider cli by passing creds as args (avoid local fs storage)

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#243]
this issue is follow up from https://github.com/gardener/gardenctl/issues/235 - we'd like to close original one and open a new one here.

We would consider security risk we if store cloud providers locally in a clear text file, the preferable method would be store them in memory.
Also we'd like to implement we can pass creds as args to gardenctl cli to access cloud provider resources.

**Comment by neo-liang-sap** [comment]
@jfortin-sap , enjoy! feel free ping me regarding the description and i will edit it.

**Comment by jfortin-sap** [comment]
@neo-liang-sap  @tedteng PR opened https://github.com/gardener/gardenctl/pull/244
