### ISSUE TITLE
Gardenctl unable to target a seed with manually deployed gardenlet

### ISSUE THREAD

**Issue by wwatson13** [gardener/gardenctl#251]
**Describe the bug**
When trying to target a seed where the gardenlet was manually deployed to an external cluster managed outside of gardener, gardenctl throws an error.

**To Reproduce**
1. Which target was set 'gardenctl get target' gardenctl --garden <value> --seed <value>
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
3. What was the output of the command:  output below:

g target -g live-virtual --seed preprod-us-gov-west-1                                                                                      ✘ 130 
Garden:
KUBECONFIG=/Users/i803548/gardens/live/garden-aws/kubeconfig
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1e4dd46]
goroutine 1 [running]:
github.com/gardener/gardenctl/pkg/cmd.targetSeed(0x22f2260, 0x2ddf120, 0x22f2280, 0x2ddf120, 0xc0003ca0a0, 0x15, 0x1)
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/target.go:452 +0x1f6
github.com/gardener/gardenctl/pkg/cmd.seedWrapper(0x22f2260, 0x2ddf120, 0x22f2280, 0x2ddf120, 0x22f2200, 0x2ddf120, 0x22f3760, 0xc0000b8000, 0x22f3780, 0xc0000b8008, ...)
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/target.go:989 +0x29c
github.com/gardener/gardenctl/pkg/cmd.NewTargetCmd.func1(0xc000362000, 0xc0002db300, 0x0, 0x4, 0x0, 0x0)
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/target.go:86 +0x5da
github.com/spf13/cobra.(*Command).execute(0xc000362000, 0xc0002db240, 0x4, 0x4, 0xc000362000, 0xc0002db240)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2da4140, 0x1d, 0xc0000b7c40, 0x36)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:864
github.com/gardener/gardenctl/pkg/cmd.Execute()
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/root.go:111 +0x3aa
main.main()
	/Users/d068290/go/src/github.com/gardener/gardenctl/cmd/gardenctl/main.go:20 +0x20

**Expected behavior**
Expected to be able to run gardenctl commands against the seed or at least a valid error statement.

**Screenshots**

**Gardenctl Version (please complete the following information):**
 gardenctl:
		version     : v0.18.0
		build date  : 2020-07-13
		go version  : go1.14.3
		go compiler : gc
		platform    : darwin/amd64
**Additional context**

**Comment by neo-liang-sap** [comment]
Hi @wwatson13 , i will ping me in private for this issue

**Comment by neo-liang-sap** [comment]
email communicated with @wwatson13 , as i can't reproduce this problem locally, meanwhile the seed `preprod-us-gov-west-1 ` is in restricted area/network hence can't provide access to me, pending customer internal discussion on how to proceed on this issue

**Comment by neo-liang-sap** [comment]
/close
close as no response from customer for two weeks.
@wwatson13 feel free ping me when you can grant me access for your env to reproduce your problem, thanks!
