### ISSUE TITLE
List orphaned resources

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#252]
**Describe the feature**
"unwanted" Infrastructure resource blocked the cluster deletion flow during the troubleshooting sometimes which also come from the latest discuss meeting `- usage e.g. gardenctl aws forceCleanupInfrastructure(String vpcId)`

what about use gardenctl  help us to check, list, and force cleanup which "unwanted" infrastructure resource blocked the process instead of using a couple of cli manually eg.
```
aws ec2 describe-security-groups --filters 'Name=vpc-id,Values='$vpc | grep ‘Security group for nodes’
aws ec2 describe-instances --filters 'Name=vpc-id,Values='$vpc | grep InstanceId
aws ec2 describe-vpn-connections --filters 'Name=vpc-id,Values='$vpc | grep VpnConnectionId
aws ec2 describe-network-interfaces --filters 'Name=vpc-id,Values='$vpc | grep NetworkInterfaceId
```

besides, different clouds need different cli to achieve it manually
 
Maybe we can to achieve the goal by automatically, To get the unwanted resource information from the error log or combine using terraform (as gardenctl support terraform cli now, maybe we can extend the terraform usage in gardenctl), diff the original infra.tf file with the latest one to find the `unwanted` infrastructure resource which blocked the cluster deletion flow. then allow us force cleanup 

---

Update following [implementation discussion](https://github.com/gardener/gardenctl/issues/252#issuecomment-676590588), this task will focus on listing the existing orphaned resources with `gardenctl infra orphan list`. We will open a follow up issue to do `gardenctl infra orphan delete`

**Comment by tedteng** [comment]
/kind/enhancement

**Comment by tedteng** [comment]
/kind/discussion

**Comment by jfortin-sap** [comment]
@tedteng Maybe to keep it simple for this iteration we can simply write the force delete logic, and improve on it later. We also need to write the logic in the cloud provider extension and call it from gardenctl. What's your thoughts on this? Lastly, we can auto-detect what cloud provider to use based on the shoot targeted so I don't think we need to specify "aws" before the function.

**Comment by tedteng** [comment]
> @tedteng Maybe to keep it simple for this iteration we can simply write the force delete logic, and improve on it later. We also need to write the logic in the cloud provider extension and call it from gardenctl. What's your thoughts on this? Lastly, we can auto-detect what cloud provider to use based on the shoot targeted so I don't think we need to specify "aws" before the function.

no issues for me, we can simply write the force delete logic first.   the `aws` just an example, because we have az/gcp as well.  I am assuming the force delete logic compatible aws/az/gcp/ali

**Comment by jfortin-sap** [comment]
@tedteng How the flow would look like to implement forceCleanupInfrastructure(String vpcId)? We need to implement it in https://github.com/gardener/gardener-extension-provider-aws i suppose and call it from there?

**Comment by jfortin-sap** [comment]
@tedteng @neo-liang-sap  Great, First I am going to attempt to call an existing example function in https://github.com/gardener/gardener-extension-provider-aws from "gardenctl forceDeleteShoot". If this works fine, I will create a PR for the extension provider.

**Comment by jfortin-sap** [comment]
@tedteng @neo-liang-sap Spoke to @dansible and we think the initial idea is too bloated. WDYT if we keep it simple and implement"gardenctl infra orphan list" to list infra resources not tracked by terraform as a first iteration, then afterwards maybe we can implement "gardenctl infra orphan delete" to remove them automatically.

**Comment by jfortin-sap** [comment]
@tedteng  @neo-liang-sap PR opened https://github.com/gardener/gardenctl/pull/278

Usage: 
go run ./cmd/gardenctl/main.go infra orphan list
(12) aws infra resources found: [vpc-0d62ce92ae70a2595 dopt-0ed0607052a170f0f subnet-0a3018d8725ce4a5a subnet-043a2f3b6305cd400 subnet-00200229c6231f6e8 sg-08c5a062596a9909c rtb-0f329835a7f9c5103 rtb-05ddd3cf5fc981e35 igw-07616a70668609fe3 nat-0cc6ccb5a12a162c7 shoot--iotedgedev--edgedev1-nodes shoot--iotedgedev--edgedev1-ssh-publickey]

No orphan aws resource found
searched /Users/i866641/.garden/cache/canary-virtual/projects/iotedgedev/edgedev1/terraform/terraform.tfstate

**Comment by tedteng** [comment]
@jfortin-sap  I did one testing, `infra orphan list` after creating one bastion. I expect it should be bastion t2.nano instance, security group for bastion and public IP for the bastion, security group ssh-access for node host.  Maybe I am on the wrong testing scenario. correct me if I missing thing. 

![image](https://user-images.githubusercontent.com/42234376/91370479-0dc8c080-e841-11ea-80c9-4d31a69a6551.png)

**Comment by jfortin-sap** [comment]
@tedteng I will add a fix to collect the bastion resources by the tag "shoot--<shoot-tag>-bastions"

**Comment by jfortin-sap** [comment]
PR opened https://github.com/gardener/gardenctl/pull/284

**Comment by jfortin-sap** [comment]
@tedteng Fixed. It will detect if a bastion host is present.

**Comment by jfortin-sap** [comment]
new PR opened to include function testing
https://github.com/gardener/gardenctl/pull/288

**Comment by jfortin-sap** [comment]
@tedteng I created a new PR and included infra_test.go but having issues with it. Do you know what is missing for infra_test.go for me to call my function? It seems it can't find getOrphanInfraResources

**Comment by tedteng** [comment]
> @tedteng I created a new PR and included infra_test.go. What command to validate my infra_test.go?

will take a look

**Comment by jfortin-sap** [comment]
@tedteng @neo-liang-sap PR https://github.com/gardener/gardenctl/pull/304 opened with AWS/Azure support, please test.

**Comment by neo-liang-sap** [comment]
Hi @jfortin-sap , i merged https://github.com/gardener/gardenctl/pull/304 and CI reports error 
```
Running gofmt...
/tmp/build/d56d9853/git-gardener_gardenctl-master_master/pkg/cmd/infra.go
/tmp/build/d56d9853/git-gardener_gardenctl-master_master/pkg/cmd/infra_test.go
Running golint...
golangci/golangci-lint info checking GitHub for tag 'v1.18.0'
golangci/golangci-lint info found version: 1.18.0 for v1.18.0/linux/amd64
golangci/golangci-lint info installed /go/bin/golangci-lint
Running golangci-lint...
pkg/cmd/infra.go:75:29: Error return value of `GetOrphanInfraResources` is not checked (errcheck)
					GetOrphanInfraResources(rs, terraformstate)
					                       ^

```

so i reverted your PR in https://github.com/gardener/gardenctl/pull/337

Could you please take a look at this PR again when available?
Thanks

**Comment by dansible** [comment]
Reopening to track remaining work for Openstack and Alicloud

**Comment by jfortin-sap** [comment]
Openstack and Alicloud PR's merged

**Comment by jfortin-sap** [comment]
OpenStack and Alicloud support PRs submitted.

**Comment by neo-liang-sap** [comment]
This issue is closed due to merge of https://github.com/gardener/gardenctl/pull/367 , i think all cloud providers are supported? Apology if i close this by mistake, @dansible @jfortin-sap 
thanks!

**Comment by vlerenc** [comment]
Sorry, I didn't tracked `gardenctl`. By accident, via the recently mentioned #475 and #477, I found this one. 

Related, @rfranzke recently proposed to pull out all resources from the Terraform file. We already pull some out to hand them over to other components (such as the VPC ID), but not yet all.

@dansible @neo-liang-sap @DockToFuture Topics like this should have been better discussed with the Gardener folks. Did that happen? I say that, because it would be a waste to duplicate the work and gardenctl couldn't reliably "follow" Gardener unless it gets released together with it, but also then it shouldn't duplicate the knowledge and details of the infrastructure extensions. This wouldn't be very sustainable long- or even mid-term.
