### ISSUE TITLE
Gardenctl does not open SSH port 22 in AWS

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardenctl#256]
**Describe the bug**
Gardenctl does not add the required inbound rule on the target ec2 instance on AWS.

**To Reproduce**

`gardenctl ssh <target-node-name>`

**Expected behavior**
Inbound rule opening port 22 in the security group of the target instance is added.

```
SSH | TCP | 22 | 0.0.0.0/0
-- | -- | -- | --
```

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - Version/Commit [Latest master commit]

**Additional context**
In AWS region eu-north-1 (Stockholm)

**Comment by tedteng** [comment]
Hi Daniel, I can't reproduce it in region eu-north-1 (Stockholm). It seems all good. 

![image](https://user-images.githubusercontent.com/42234376/90133549-4200a380-dda2-11ea-98e2-cdbb35b0c69f.png)
![image](https://user-images.githubusercontent.com/42234376/90133559-44fb9400-dda2-11ea-9761-4d45327b9a6d.png)

**Comment by tedteng** [comment]
Hi Daniel, I can't reproduce it in region eu-north-1(Stockholm) It seems all good.

![image](https://user-images.githubusercontent.com/42234376/90133754-9c99ff80-dda2-11ea-8b80-e232efe806f7.png)
![image](https://user-images.githubusercontent.com/42234376/90133781-a58ad100-dda2-11ea-9fa1-fbfac29f5483.png)

**Comment by danielfoehrKn** [comment]
I realised that in my local setup the infrastructure CRD was constantly reconciling, thus  it is constantly removing the security group.
Thanks.
