### ISSUE TITLE
Bastion host IP missing  

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#257]
**Describe the bug**
Bastion IP missing which cause security group create failure. 

```
(2/4) Setting up bastion host security group
Bastion host security group set up.

An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupIngress operation: CIDR block /32 is malformed
exit status 2
```

**To Reproduce**
gardenctl ssh hostname

**Expected behavior**
gardenctl ssh bastion host

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - Version/Commit [latest master]

**Additional context**

PR:  https://github.com/gardener/gardenctl/pull/258

**Comment by tedteng** [comment]
revert PR https://github.com/gardener/gardenctl/pull/258

**Comment by tedteng** [comment]
Hi @jfortin-sap  Please take a look. I think the line 67 want to create host security group, but the bastion IP generated at line 73. which cause the issue host security group failure due to a.bastion IP null in line 67
https://github.com/gardener/gardenctl/blob/a8dd668f063df995355d39a9f6cc6964c868f00a/pkg/cmd/ssh_aws.go#L66-L73

maybe move 
https://github.com/gardener/gardenctl/blob/a8dd668f063df995355d39a9f6cc6964c868f00a/pkg/cmd/ssh_aws.go#L183-L189

to 	a.createBastionHostInstance()

**Comment by jfortin-sap** [comment]
@tedteng I see, I will fix

**Comment by jfortin-sap** [comment]
@tedteng I think it is an ordering issue and we should consider moving the function "a.createBastionHostSecurityGroup()" after a.createBastionHostInstance() because we can only retrieve the BastionIP once the instance is created.

**Comment by jfortin-sap** [comment]
PR opened https://github.com/gardener/gardenctl/pull/261

**Comment by jfortin-sap** [comment]
@tedteng  @neo-liang-sap  PR opened https://github.com/gardener/gardenctl/pull/261
