### ISSUE TITLE
Add an option for Gardenctl to enable global log level

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#259]
In https://github.com/gardener/gardenctl/issues/234, gardenerLogger is introduced, the log level could be specified via:
```
var logger = gardenerlogger.NewLogger("info")
```

We would like to check whether it is possible to add an option for gardenctl commandline e.g. `gardenctl -v=info` to specify globally the log level.

**Comment by danielfoehrKn** [comment]
It would be nice if logging on the debug level would include verbose output for the `ssh` command itself (not only gardenctl ssh)

**Comment by tedteng** [comment]
> It would be nice if logging on the debug level would include verbose output for the `ssh` command itself (not only gardenctl ssh)

will take care of that. I already enable this in my local code will open PR for that.

**Comment by tedteng** [comment]
@danielfoehrKn  Please have a look PR: check https://github.com/gardener/gardenctl/pull/264. I was also want to set the global flag before, but working on another allow non-operator ssh node ticket doesn't have time working on that. Base on the global flag concept,  two enhance in this PR. 
1. ssh  Verbose mode 

2. Error msg enhance 
I try adopt `logger.Debugf` but not too much useful information as before, maybe I get wrong ways when use `logger.Debugf` 
``` 
gg target -g ttt -p i333878 -t zegfzwjhzh -d
Garden:
KUBECONFIG=/Users/i333878/gardener_kubeconfig/ttt/kubeconfig
time="2020-08-20T08:42:35+08:00" level=debug msg="secrets \"seed-aws-eu1\" is forbidden: User \"system:serviceaccount:garden-i333878:robot\" cannot get resource \"secrets\" in API group \"\" in the namespace \"garden\""
exit status 2
```

after change, it looks like this when we call ErrorCheck
```
gg target -g ttt -p i333xxx -t zegfzwjhzh -d
Garden:
KUBECONFIG=/Users/i333xxx/gardener_kubeconfig/ttt/kubeconfig
2020/08/20 08:51:51 [error] /Users/i333xxx/Work/tedteng/gardenctl/pkg/cmd/target.go:568 
 secrets "seed-aws-eu1" is forbidden: User "system:serviceaccount:garden-i333xxx:robot" cannot get resource "secrets" in API group "" in the namespace "garden"
exit status 2
```
