### ISSUE TITLE
Allow creation of bastion using Worker YAML by default

### ISSUE THREAD

**Issue by dansible** [gardener/gardenctl#272]
Follow up from https://github.com/gardener/gardenctl/issues/236, we would like to use the MCM by default to create the bastion worker resource. If the MCM is not available, we can keep the exiting hyperscaler VM creation as a backup (by using a flag like `gardenctl ssh <NODE> --hyperscaler`)

**Comment by tedteng** [comment]
/assign 
seems all `user` role part completed will working on this.

**Comment by tedteng** [comment]
after testing, from creating VM perspective The MCM fetching information from YAML [aws-class](https://github.com/gardener/machine-controller-manager/blob/master/kubernetes/machine_classes/aws-machine-class.yaml) and [machine.yaml](https://github.com/gardener/machine-controller-manager/blob/master/kubernetes/machine_objects/machine.yaml) using https://github.com/aws/aws-sdk-go as core code to management VM. It is similar to when we using aws-cli.  

if we adopt https://github.com/aws/aws-sdk-go to create vm function, it seems not too many advantages for ours.  as aws-sdk-go and aws-cli is the same feature provider by aws.   so I am planning close the issue

**Comment by dansible** [comment]
closing as we are re-using the same methodology for creating the vms. The deletion process is already part of the ssh flow in gardenctl - no need to use mcm
