### ISSUE TITLE
refactor `ExecCmdReturnOutput` usage of `curl` to use API access

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#273]
This is a sub-issue for https://github.com/gardener/gardenctl/issues/266
the refactor of curl part will be logged here

`ExecCmdReturnOutput("bash", "-c", "curl <something>")`

**Comment by neo-liang-sap** [comment]
test 
/invite @dansible

**Comment by tedteng** [comment]
got some issue, not sure just in my local env. 

gg ssh ip-10-250-6-9.eu-central-1.compute.internal

Warning:
Be aware that you are entering an untrusted environment!
Do not enter credentials or sensitive data within the ssh session that cluster owners should not have access to.

```
Downloaded id_rsa key
Check Public IP
Get "https%3A%2F%2Fapi.ipify.org%3Fformat%3Dtext": unsupported protocol scheme ""
exit status 2
```
![image](https://user-images.githubusercontent.com/42234376/91412664-acbede00-e87c-11ea-9da3-5b7b34eca8e7.png)

**Comment by neo-liang-sap** [comment]
Hi @petersutter , i think here we need to remove `url.QueryEscape()`.
if we have url.QueryEscape(), the url would be "https%3A%2F%2Fapi.ipify.org%3Fformat%3Dtext"
without url.QueryEscape(), the url would be "https://api.ipify.org?format=text", this is what we want

**Comment by petersutter** [comment]
hi @neo-liang-sap yes see also my comment here https://github.com/gardener/gardenctl/pull/274/files#r478248871
