### ISSUE TITLE
ipv4 check after get public IP

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#275]
**Describe the bug**
in some rare case public ip return ipv6. 

 ```
(2/4) Setting up bastion host security group
aws ec2 authorize-security-group-ingress --group-id sg-0ccef1d8a628a6a91 --protocol tcp --port 22 --cidr 240e:e0:f090:34bb:bd78:6c06:e328:9b79/32

An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupIngress operation: CIDR block 240e:e0:f090:34bb:bd78:6c06:e328:9b79/32
```

**To Reproduce**
gardenctl ssh node

**Expected behavior**
ipv4 return

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - Version/Commit [latest version]

**Additional context**

**Comment by petersutter** [comment]
`aws ec2 authorize-security-group-ingress` should also work with ipv6 addresses according to the documentation, doesn't it? However the command slightly needs to be adapted in case of ipv6 addresses

**Comment by tedteng** [comment]
sure not doubt that

**Comment by petersutter** [comment]
I also don't know, maybe @DockToFuture knows. 
But I guess it makes sense to add support for ipv6 if we don't already have it so that we do not `os.exit` in case it's not an ipv4 address as in #276

```go
	if !isIP(string(ip)) {
		fmt.Println("Not valid ipv4 address")
		os.Exit(1)
	}
```

**Comment by tedteng** [comment]
> I also don't know, maybe @DockToFuture knows.
> But I guess it makes sense to add support for ipv6 if we don't already have it so that we do not `os.exit` in case it's not an ipv4 address as in #276
> 
> ```go
> 	if !isIP(string(ip)) {
> 		fmt.Println("Not valid ipv4 address")
> 		os.Exit(1)
> 	}
> ```

fixed, Please have a look and the testing result 

![image](https://user-images.githubusercontent.com/42234376/91512779-5baef880-e915-11ea-8f1a-6959b2b4d776.png)
