### ISSUE TITLE
gardenctl `aws|gcp...` rely that project will be targeted

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/gardenctl#295]
**Describe the bug**
`gardenctl` expects that project will be targeted in cmd/operate.go
https://github.com/gardener/gardenctl/blob/master/pkg/cmd/operate.go#L47 

In this way if `gardenctl aws ...` is called and the Path to the shoot is constructed by using its seed, the command will fail with
```
projects.core.gardener.cloud "<seed-name>" not found
```

**To Reproduce**
g target garden... -> g target seed... -> g target shoot ...

**Expected behavior**
It should also expect that the Target can be constructed using `seed` instead of `project`

**Comment by tedteng** [comment]
Hi @Kristian-ZH, to suitable `user` role able to access aws|gcp as well, I currently working on `operate.go` part.  If I understanding correctly, You want to target shoot first then `gardenctl aws` right. 
something like 
`gardenct -g canary-virtual -p project -t shoot` 
then 
`gardenctl aws`  ?

**Comment by neo-liang-sap** [comment]
> Hi @Kristian-ZH, to suitable `user` role able to access aws|gcp as well, I currently working on `operate.go` part. If I understanding correctly, You want to target shoot first then `gardenctl aws` right.
> something like
> `gardenct -g canary-virtual -p project -t shoot`
> then
> `gardenctl aws` ?

@Kristian-ZH is DOD and have same acccess/role with SRE, this issue has nothing to do with role, i'm currently work on it.
