### ISSUE TITLE
No error message when cloud client is not present

### ISSUE THREAD

**Issue by dansible** [gardener/gardenctl#299]
**Describe the bug**
When the cloud provider client is not installed, `gardenctl` should error to explain that it is missing. Currently it just exits silently

**To Reproduce**
1. Target a shoot
2. Make sure `aws | az | gcloud | openstack` is not installed
3. Run `gardenctl <aws|az|gcloud|openstack> -- --help` 

**Expected behavior**
`gardenctl` should return with an error to say that the cli utility is not installed

**Gardenctl Version (please complete the following information):**
 - `v0.21.0`

**Comment by neo-liang-sap** [comment]
good catch! i will fix this!
/assign
