### ISSUE TITLE
kubernetes dashboard `/ui` redirect is now removed

### ISSUE THREAD

**Issue by bergerx** [gardener/gardenctl#30]
Recently in Kubernetes dashboard deprecated the `/ui` redirect: https://github.com/kubernetes/kubernetes/pull/53766

`gardenctl show dashboard` still tries to open `http://127.0.0.1:8002/ui` which is not valid anymore.

URL should now be:
```
http://localhost:8002/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/
```

**Comment by DockToFuture** [comment]
Thanks for reporting, is now fixed.
