### ISSUE TITLE
Gardenctl ssh fails when targeting a non unique shoot name

### ISSUE THREAD

**Issue by schrodit** [gardener/gardenctl#312]
**Describe the bug**

Gardenctl is unable to ssh into a node if there are multiple shoots in one gardener instance with the same name.
When running `gardenctl ssh` on a shoot with a non unique name, gardenctl is unable to determine the correct context and tries to access the seed of the other shoot: `Error: stat /Users/xxx/.garden/cache/live/seeds/other-seed/kubeconfig.yaml: no such file or directory`

**To Reproduce**
Create 2 shoots with the same name in different projects
1. target one of the shoots.
2. `gardenctl ssh`
3. `Error: stat /Users/xxx/.garden/cache/live/seeds/other-seed/kubeconfig.yaml: no such file or directory`

**Expected behavior**
Gardenctl should be able ssh into a node even if there are multiple shoots with the same name

**Gardenctl Version (please complete the following information):**
 - v0.21.0

**Additional context**
cc @DockToFuture please correct or add your observations to the description.

**Comment by tedteng** [comment]
> **To Reproduce**
> Steps to reproduce the behavior:
> Create 2 shoots with the same name in different projects

how about if using `gardenctl -g garden -p project_name -t shoot`  ?

**Comment by schrodit** [comment]
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > Create 2 shoots with the same name in different projects
> 
> how about if using `gardenctl -g garden -p project_name -t shoot` then `gardenctl ssh` , is the issue still exist ?

we tried that but with the same outcome.

**Comment by tedteng** [comment]
thanks, I am checking on that.

**Comment by tedteng** [comment]
@schrodit  fixed now If you need you can cheery-pick from the PR #315 to build it on local before we release the new version

**Comment by schrodit** [comment]
@tedteng thanks for the quick fix. Will try it out as soon as we need it again
