### ISSUE TITLE
Enable `gardenctl logs gardenlet`

### ISSUE THREAD

**Issue by dansible** [gardener/gardenctl#320]
It would be great if we could get the logs of the gardenlet component (operator only) using `gardenctl logs`

**Comment by neo-liang-sap** [comment]
Hi @tedteng , have you ever begin working on this issue? currently i see you have three issues opening (except this one) and two PRs ongoing (one of them in draft), as we discussed before in planning mtg, it would be much better to keep an issue unassigned unless you started working on this, hence other people with availability / bandwidth could work on this.
what do you think?
cc @dansible @jfortin-sap

**Comment by tedteng** [comment]
yes just working on that today. 

Three issues opening (except this one) and two PRs ongoing (one of them in draft), 
for those two issue tickets one under review status, one dependence the ticket which under review (some new method need using)

I think the two PRs ongoing you mention, one is draft which belong is the dependence ticket, and another one is ticket under review status.

**Comment by tedteng** [comment]
> Hi @tedteng , have you ever begin working on this issue? currently i see you have three issues opening (except this one) and two PRs ongoing (one of them in draft), as we discussed before in planning mtg, it would be much better to keep an issue unassigned unless you started working on this, hence other people with availability / bandwidth could work on this.
> what do you think?
> cc @dansible @jfortin-sap

besides, I think we also have new issue open on the epic you can take a look if you are interesting. 
https://github.com/gardener/gardenctl/issues/267#issuecomment-696187590

**Comment by neo-liang-sap** [comment]
> besides, I think we also have new issue open on the epic yesterday you can take a look if you are interesting.
> [#267 (comment)](https://github.com/gardener/gardenctl/issues/267#issuecomment-696187590)
i see in this issue you are assignee - if you don't plan to continue work on this , could you please change it to unassign? this might be confusing for other people to know whether you are still workin on this

**Comment by tedteng** [comment]
> > besides, I think we also have new issue open on the epic yesterday you can take a look if you are interesting.
> > [#267 (comment)](https://github.com/gardener/gardenctl/issues/267#issuecomment-696187590)
> 
> i see in this issue you are assignee - if you don't plan to continue work on this , could you please change it to unassign? othwesie it might be confusing for other people to know whether you are still workin on this

sure, np. The issue reopens yesterday. Like me carete the ticket. you can assign it.
