### ISSUE TITLE
Sanitize user input in drop.go

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#327]
**Describe the bug**

Sanitize user input when executing local commands as much as possible

This is one of the sub-task for ticket https://github.com/gardener/gardenctl/issues/267

**Comment by neo-liang-sap** [comment]
duplicate with my PR https://github.com/gardener/gardenctl/pull/324

**Comment by tedteng** [comment]
> duplicate with my PR #324

I think this ticket is more about sanitize `bash -c`

and the issue ticket you are working is seems more about refacot the `ExecCmd` function itself , but you can check with Peter for more information. 

`ExecCmd should not be called with a cmd string and instead the caller should pass the name and arguments directly for exec.Command, otherwise an attacker could sneak in arguments`

**Comment by neo-liang-sap** [comment]
totally not getting your point, for my PR i'm refactoring `ExecCmdReturnOutput` in drop.go

**Comment by tedteng** [comment]
> totally not getting your point, for my PR i'm refactoring `ExecCmdReturnOutput` in drop.go

so you are not working on refactor ExecCmd function right  https://github.com/gardener/gardenctl/issues/267#issuecomment-696187590.  I will create new issue ticket for that

**Comment by neo-liang-sap** [comment]
/close
as pr merged
