### ISSUE TITLE
getRole() function is not returning correct role

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#330]
**Describe the bug**
i'm admin in both landscapes (sorry i can't say the names here but ping me in private to get the names)
but getRole() function returns i'm `user`

**To Reproduce**
1. insert fmt.Println(getRole()) in `target.go`, `targetShoot` function
2. build the gardenctl
3.target some shoot
![image](https://user-images.githubusercontent.com/42594392/93858169-506da380-fcee-11ea-9320-75d4a6836806.png)
![image](https://user-images.githubusercontent.com/42594392/93858207-5cf1fc00-fcee-11ea-914a-89725ab9077b.png)

my code snippet here:
![image](https://user-images.githubusercontent.com/42594392/93858259-76934380-fcee-11ea-8112-8ae80769cde6.png)
 
Do let me know if it's due to my mis-use of getRole() function

**Expected behavior**
getRole() should return i'm admin

**Screenshots**
**Gardenctl Version (please complete the following information):**
 - Version/Commit [35db66bc]

**Additional context**
@tedteng  FYI

**Comment by petersutter** [comment]
@neo-liang-sap when you target the garden cluster and run `kubectl auth can-i get secrets`, what is returned?

**Comment by neo-liang-sap** [comment]
Hi @petersutter , thanks for comments, i got `yes` in both env
![image](https://user-images.githubusercontent.com/42594392/93866852-cd9f1580-fcfa-11ea-92cf-4a62cc623bfc.png)

**Comment by petersutter** [comment]
can you debug the getRole function? 

```go
func getRole() string {
	var target Target
	var role string
	ReadTarget(pathTarget, &target)
	clientset, err := target.K8SClientToKind("garden")
	checkError(err)
	ssar := &authorizationv1.SelfSubjectAccessReview{
		Spec: authorizationv1.SelfSubjectAccessReviewSpec{
			ResourceAttributes: &authorizationv1.ResourceAttributes{
				Verb:     "get",
				Resource: "secret",
			},
		},
	}
	ssar, err = clientset.AuthorizationV1().SelfSubjectAccessReviews().Create(ssar)
	checkError(err)
	if ssar.Status.Allowed {
		role = "operator"
	} else {
		role = "user"
	}
	return role
}
```

what are the values of 
- `ssar.Status.Denied`
- `ssar.Status.Reason`
- `ssar.Status.EvaluationError`
- `ssar.Status.Allowed` is obviously false..

**Comment by neo-liang-sap** [comment]
Hi @petersutter , i add debug information in getRole() and here's return
![image](https://user-images.githubusercontent.com/42594392/93878164-2fb44680-fd0c-11ea-937e-804c4a019ff8.png)
`ssar.Status.Reason` and `ssar.Status.EvaluationError` are empty

Here's code snippet i used in getRole() to get these values
```
func getRole() string {
	var target Target
	var role string
	ReadTarget(pathTarget, &target)
	clientset, err := target.K8SClientToKind("garden")
	checkError(err)
	ssar := &authorizationv1.SelfSubjectAccessReview{
		Spec: authorizationv1.SelfSubjectAccessReviewSpec{
			ResourceAttributes: &authorizationv1.ResourceAttributes{
				Verb:     "get",
				Resource: "secret",
			},
		},
	}
	ssar, err = clientset.AuthorizationV1().SelfSubjectAccessReviews().Create(ssar)
	checkError(err)
	if ssar.Status.Allowed {
		role = "operator"
	} else {
		role = "user"
	}
	fmt.Println("ssar.Status.Denied " + strconv.FormatBool(ssar.Status.Denied))
	fmt.Println("ssar.Status.Reason " + ssar.Status.Reason)
	fmt.Println("ssar.Status.EvaluationError " + ssar.Status.EvaluationError)
	fmt.Println("ssar.Status.Allowed " + strconv.FormatBool(ssar.Status.Allowed))
	return role
}
```

**Comment by petersutter** [comment]
Can you figure out if really the correct kubeconfig is used.
`clientset, err := target.K8SClientToKind("garden")`

E.g. print out `pathToKubeconfig` (somewhere deep in `target.K8SClientToKind("garden")`). Then use this kubeconfig to for your local kubectl and run the command from above again.

**Comment by neo-liang-sap** [comment]
Hi @petersutter ,
I tried to print `pathToKubeconfig ` in `target.K8SClientToKind("garden")` but it seems to be an empty string "".
I step into `target.K8SClientToKind()` and in `clientToTarget` i print out the `[]byte kubeconfig`, the value is the centralized kubeconfig with OIDC enabled (Donka sent an email to everyone for the content, i can't share the content here but i believe definitely you have that one)

This kubeconfig (Donka sent, OIDC enabled) locates in my Mac `~/.kube/config`
if i export KUBECONFIG to this file i'm unable to execute `kubectl auth can-i get secrets`

![image](https://user-images.githubusercontent.com/42594392/93881270-427d4a00-fd11-11ea-9cf9-352d926325b0.png)

**Comment by neo-liang-sap** [comment]
in offline discussion with @petersutter

**Comment by tedteng** [comment]
It seems no issue in my place.  It return operator


![image](https://user-images.githubusercontent.com/42234376/93888800-0cdd5e80-fd1b-11ea-9083-72e193c70a6c.png)

**Comment by neo-liang-sap** [comment]
@tedteng , what's your content of /Users/ixxxx/gardener_kubeconfig/canary/garden-gke/kubeconfig? is this the centralized one with OIDC enabled (sent by Donka) or the traditional one (before OIDC enabled)? 
i believe yours is the old one because if you are using the new one, you will have to `gardenctl target canary`, not `gardenctl target canary-virtual`
FYI i had a half hour screensharing debuging with @petersutter and witnessed the problem, currently Peter is checking from his side

**Comment by petersutter** [comment]
I could reproduce it, it has indeed something to do with the oidc configuration in the kubeconfig

**Comment by tedteng** [comment]
sure, Thanks guys, so the issue will not related with getRole() right ?

**Comment by neo-liang-sap** [comment]
it definitely related to getRole() - OIDC has been force enabled for quite a long time and getRole() is not working under OIDC env
