### ISSUE TITLE
using traits to trigger auto update for https://github.com/gardener/ops-toolbelt/

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#336]
each gardenctl release , the version number of https://github.com/gardener/ops-toolbelt/blob/master/dockerfile-configs/gardenctl-components.yaml#L22 needs to be updated.
will investigate this issue to use traits to trigger auto update for https://github.com/gardener/ops-toolbelt/

**Comment by petersutter** [comment]
@neo-liang-sap updating ops-toolbelt once a new gardenctl release is done should already be possible with https://gardener.github.io/cc-utils/traits/update_component_deps.html (using `Upgrade Pull Requests`). In case you have questions you can also ping the cc-utils maintainers

**Comment by neo-liang-sap** [comment]
thanks @petersutter , i never know this before, i reached @AndreasBurger offline in email to know more details.

**Comment by neo-liang-sap** [comment]
PR - https://github.com/gardener/ops-toolbelt/pull/35

**Comment by neo-liang-sap** [comment]
/close
as PR https://github.com/gardener/ops-toolbelt/pull/35 already merged
