### ISSUE TITLE
Add node tolerations for gardenctl shell

### ISSUE THREAD

**Issue by dansible** [gardener/gardenctl#338]
When nodes have specific taints, `gardenctl shell` is not able to schedule a pod on those nodes. We would like to add generic tolerations that will allow the pod to run on any node

See the toolbelt hack for info: https://github.com/gardener/ops-toolbelt/blob/master/hacks/ops-pod

Once this is added, it would be great if we can remove the `ops-toolbelt` script so that we aren't duplicating code

**Comment by neo-liang-sap** [comment]
/assign
i will work on this one

**Comment by neo-liang-sap** [comment]
i checked ops-pod source code file https://github.com/gardener/ops-toolbelt/blob/master/hacks/ops-pod#L121-L124
in `gardenctl shell` we already have similar tolerations https://github.com/gardener/gardenctl/blob/master/pkg/cmd/shell.go#L227-L233
so this issue is already code ready?
@dansible

**Comment by dansible** [comment]
Is it possible to add a more generic toleration for all nodes that have `NoSchedule`/`NoExecute` effects regardless of key? ie:

from:
```
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
```

to:
```
  tolerations:
  - effect: NoSchedule
  - effect: NoExecute
```

**Comment by dansible** [comment]
If not, then yes, let's close this issue 👍

**Comment by neo-liang-sap** [comment]
Hi @dansible , please see my PR and comments in https://github.com/gardener/gardenctl/pull/386
