### ISSUE TITLE
Binary distribution of gardenctl

### ISSUE THREAD

**Issue by bergerx** [gardener/gardenctl#34]
Is it possible to make versioned releases of `gardenctl` and have a binary distribution. After the recent shoot namespace adaptation everyone in my team had to manually compile the binary, we've been thinking about compiling it for 3 main platforms (macos, linux and windows) and making it available internally.

It would be more beneficial for everyone if thats done on upstream.

**Comment by vlerenc** [comment]
You are right, that's still missing, FYI: We are also thinking in the direction of #12.

**Comment by bergerx** [comment]
I briefly checked but dont understand which ci tool is in use.
Is there any way that we can help in implementing a binary distribution for this issue?

**Comment by DockToFuture** [comment]
We are using concurse and the first release of gardenctl was created for mac and linux.

**Comment by msohn** [comment]
looks like we lack public documentation about ci tools and process we use, I asked the ci team if they can have a look and fix this

**Comment by bergerx** [comment]
Thanks a lot for the quick response, this is really helpful for us.
