### ISSUE TITLE
Gardenctl cant operate on garden clusters deployed on 1.11

### ISSUE THREAD

**Issue by bergerx** [gardener/gardenctl#35]
**Describe the bug**
Gardenctl doesnt work on gardens deployed on 1.11 kubernetes clusters.

**To Reproduce**
1. Upgrade a garden kubernetes cluster to 1.11.
2. `gardenctl ls seeds`
3. gardenctl reports `Kubernetes cluster has version v1.11.1 which is not supported`

**Expected behavior**
gardenctl to operate on garden cluster.

**Screenshots**
```sh
$ gardenctl ls seeds
Kubernetes cluster has version v1.11.1 which is not supported
```

**Gardenctl Version (please complete the following information):**
- commit acb0f725632867345b6dc89495b0682af92127a1

**Comment by DockToFuture** [comment]
Dependencies were updated and work now with kubernetes 1.11.
