### ISSUE TITLE
show alertmanager not working

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#350]
`show alertmanger` not working but not sure whether still needed? 

"The code in here maybe lack of maintenance, I found the alert manager is not working. 

k get ingress -n shoot--i333878--aws-users-role -o name
ingress.extensions/dashboard-terminal-kube-apiserver
ingress.extensions/grafana-operators
ingress.extensions/grafana-users
ingress.extensions/prometheus"

_Originally posted by @tedteng in https://github.com/gardener/gardenctl/pull/319#r494791643_

**Comment by neo-liang-sap** [comment]
/assign
ingress alertmanager not exist any more, will remove the code
![image](https://user-images.githubusercontent.com/42594392/96682823-ee1ac800-13ab-11eb-8a5e-84904e28b9d5.png)
