### ISSUE TITLE
gardenctl should have a way to print its version

### ISSUE THREAD

**Issue by epierotto** [gardener/gardenctl#36]
**Describe the bug**
gardenctl should have a way to print its version

**To Reproduce**
`gardenctl` does not show any possible way to display its version.

**Expected behavior**
As `gardenctl` user I would like to know which version I'm using by just issuing a `gardenctl` command.

Example:
`gardenctl version` (This is how version display is implemented on `kubectl` and `helm`)

**Gardenctl Version (please complete the following information):**

**Additional context**

**Comment by DockToFuture** [comment]
Feature was added with first release
