### ISSUE TITLE
gardencl does not support K8s v1.11.2

### ISSUE THREAD

**Issue by esimeon-ptc** [gardener/gardenctl#37]
**Describe the bug**
gardencl does not support K8s v1.11.2

**To Reproduce**
$ ./gardenctl ls gardens
gardenClusters:
- name: cloud-garden-01

$ ./gardenctl ls shoots
Kubernetes cluster has version v1.11.2 which is not supported

$ ./gardenctl ls seeds
Kubernetes cluster has version v1.11.2 which is not supported

**Attitude of gratitude (AoG)**
Thank you in advance for your help

**Comment by bergerx** [comment]
I guess you meant 1.11.2, rather than 1.11.12 (as you wrote 1.11.12 in title and description)? 

Very recently a pipeline and release support added to this repo, so you can check https://github.com/gardener/gardenctl/releases/tag/0.2.0

**Comment by esimeon-ptc** [comment]
Thx, I fixed the typo

**Comment by bergerx** [comment]
I updated my comment after yours, can you try with latest release, it should be working.

**Comment by esimeon-ptc** [comment]
Thank you for the quick response, 
The latest release tested ok.
 https://github.com/gardener/gardenctl/releases/tag/0.2.0

**Comment by esimeon-ptc** [comment]
Thanks again for your help.
I was able to retrace my steps.
Visited Gardenctl repo and I cut-n-paste the curl command under Installation.
The link is hard coded to 0.1.0 version.
 
Installation
gardenctl is shipped for mac and linux in a binary format. The easiest way to install it, is to download the file or curl it.

curl -LO https://github.com/gardener/gardenctl/releases/download/0.1.0/gardenctl-darwin-amd64
