### ISSUE TITLE
alicloud ssh key not accessible

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#372]
**Describe the bug**
```
(5/5) Starting bastion host
Starting bastion host...
Waiting for bastion host to start...
Waiting for bastion host to start...
Waiting for bastion host to start...
Waiting for bastion host to start...
Waiting for bastion host to start...
Waiting for bastion host to start...
Bastion host started.
Allocating bastion host IP address...
Bastion host IP address allocated.
Bastion host started.
Warning: Identity file /Users/i333878/.garden/cache/canary/projects/i333878/ali-ali-001key not accessible: No such file or directory.
Warning: Identity file /Users/i333878/.garden/cache/canary/projects/i333878/ali-ali-001key not accessible: No such file or directory.
ssh: connect to host 47.254.170.147 port 22: Operation timed out
kex_exchange_identification: Connection closed by remote host
exit status 255
Would you like to cleanup the created bastion? (y/n)
y
Cleanup
Cleaning up bastion host configurations...
```

**To Reproduce**
ssh alinode

**Expected behavior**

**Screenshots**

**Gardenctl Version (please complete the following information):**
gardenctl:
                version     : v0.21.0
                build date  : 2020-08-23
                go version  : go1.14.6
                go compiler : gc
                platform    : darwin/amd64

**Additional context**

**Comment by neo-liang-sap** [comment]
```
/Users/i352986/.garden/cache/canary/projects/garden/alicloud-eu1key
```
actually the key is /Users/i352986/.garden/cache/canary/projects/garden/alicloud-eu1/key,  missing a `/`
will investigate why key for alicloud missing a `/` in path

**Comment by tedteng** [comment]
I think there two issues in alicloud, but I don't have time to check ssh issue deeply at that time when I open the issue.  
one is `\` missing and another is ssh connection failure.
```
(5/5) Starting bastion host
Starting bastion host...
Waiting for bastion host to start...
Waiting for bastion host to start...
Waiting for bastion host to start...
Waiting for bastion host to start...
Waiting for bastion host to start...
Waiting for bastion host to start...
Bastion host started.
Allocating bastion host IP address...
Bastion host IP address allocated.
Bastion host started.
ssh: connect to host 47.254.174.139 port 22: Operation timed out
kex_exchange_identification: Connection closed by remote host
exit status 255
Would you like to cleanup the created bastion? (y/n)
```

issue one
```
Warning: Identity file /Users/i333878/.garden/cache/canary/projects/i333878/ali-ali-001key not accessible: No such file or directory.
Warning: Identity file /Users/i333878/.garden/cache/canary/projects/i333878/ali-ali-001key not accessible: No such file or directory.
```
issue two
```
ssh: connect to host 47.254.170.147 port 22: Operation timed out
kex_exchange_identification: Connection closed by remote host
exit status 255
```

**Comment by neo-liang-sap** [comment]
> I think there two issues in alicloud, but I don't have time to check ssh issue deeply at that time when I open the issue.
> one is `\` missing and another is ssh connection failure.
> 
> ```
> (5/5) Starting bastion host
> Starting bastion host...
> Waiting for bastion host to start...
> Waiting for bastion host to start...
> Waiting for bastion host to start...
> Waiting for bastion host to start...
> Waiting for bastion host to start...
> Waiting for bastion host to start...
> Bastion host started.
> Allocating bastion host IP address...
> Bastion host IP address allocated.
> Bastion host started.
> ssh: connect to host 47.254.174.139 port 22: Operation timed out
> kex_exchange_identification: Connection closed by remote host
> exit status 255
> Would you like to cleanup the created bastion? (y/n)
> ```
> 
> issue one
> 
> ```
> Warning: Identity file /Users/i333878/.garden/cache/canary/projects/i333878/ali-ali-001key not accessible: No such file or directory.
> Warning: Identity file /Users/i333878/.garden/cache/canary/projects/i333878/ali-ali-001key not accessible: No such file or directory.
> ```
> 
> issue two
> 
> ```
> ssh: connect to host 47.254.170.147 port 22: Operation timed out
> kex_exchange_identification: Connection closed by remote host
> exit status 255
> ```

yes you are absolutely right, i opened https://github.com/gardener/gardenctl/issues/379 to track your issue two, thanks for reminding!
