### ISSUE TITLE
v0.22.0 gardenctl unable to operate against aws/gcp/azure cloud providers

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#389]
**Describe the bug**

This bug is introduced in https://github.com/gardener/gardenctl/pull/368
Now the issue is (same for aws/gcp/azure):

1) when run some cloud provider command e.g. `gardenctl aws ec2 describe-instances`, the actually command running is `gardenctl aws aws ec2 describe-instances`, so the `aws` command will exit with error code.
The problem code is https://github.com/gardener/gardenctl/pull/368/commits/d5677ca1b31d3769881cb5dd608b95c22025813c#diff-35cfdbb008094fbcbebfc8909edc59f44d1290e38a3bdd9da5c08b5fadff1de7R90

the `args` already contains cloud provider command e.g. `aws` and in next line, `aws` is append again

2) even the 1) is fixed, `gardenctl aws ec2 describe-instances` will display nothing.

the problem code is https://github.com/gardener/gardenctl/pull/368/commits/d5677ca1b31d3769881cb5dd608b95c22025813c#diff-35cfdbb008094fbcbebfc8909edc59f44d1290e38a3bdd9da5c08b5fadff1de7R94

previous code will return command output but now it displays nothing
```
err := ExecCmd(nil, arguments, false, "AWS_ACCESS_KEY_ID="+string(accessKeyID[:]), "AWS_SECRET_ACCESS_KEY="+string(secretAccessKey[:]), "AWS_DEFAULT_REGION="+region, "AWS_DEFAULT_OUTPUT=text")
```

Above 1) and 2) issues applies for gcp/aws/azure

**To Reproduce**
1. target a gcp/aws/azure
2. gardenctl aws/gcp/azure
3. nothing is displayed

**Expected behavior**
error should not occur

**Screenshots**

**Gardenctl Version (please complete the following information):**
v0.22.0
**Additional context**

**Comment by neo-liang-sap** [comment]
Per discussion with @dansible i'm providing an ugly hotfix https://github.com/gardener/gardenctl/pull/390/

**Comment by neo-liang-sap** [comment]
/reopen
the fix i provided is a temp/ugly/quick fix, if anyone has better refactor idea feel free re-design the fix

**Comment by tedteng** [comment]
PR for the subcommand https://github.com/gardener/gardenctl/pull/391. maybe we can revoke #390

**Comment by tedteng** [comment]
Its all good for 

AWS:
```
gg aws ec2 describe-instances -- --instance-id i-0651db1613a04e70a
RESERVATIONS	802691470131	r-07391c0be8c7bb9f0
INSTANCES	0	x86_64		False	True	xen	ami-01fffc8f3a3797140	i-0651db1613a04e70a	t2.micro	dirk-test	2020-09-24T15:22:56+00:00	ip-172-31-15-39.eu-central-1.compute.internal	172.31.15.39	ec2-18-159-254-72.eu-central-1.compute.amazonaws.com	18.159.254.72	/dev/xvda	ebsTrue		subnet-7bb43136	hvm	vpc-0ec41265
BLOCKDEVICEMAPPINGS	/dev/xvda
EBS	2020-09-24T15:22:57+00:00	True	attached	vol-0df2175c60996d337
CAPACITYRESERVATIONSPECIFICATION	open
CPUOPTIONS	1	1
HIBERNATIONOPTIONS	False
METADATAOPTIONS	enabled	1	optional	applied
MONITORING	disabled
NETWORKINTERFACES		interface	0a:30:68:13:9a:52	eni-0e2117f1d3aef2ed2	802691470131	ip-172-31-15-39.eu-central-1.compute.internal	172.31.15.39	True	in-use	subnet-7bb43136	vpc-0ec41265
ASSOCIATION	amazon	ec2-18-159-254-72.eu-central-1.compute.amazonaws.com	18.159.254.72
ATTACHMENT	2020-09-24T15:22:56+00:00	eni-attach-0ac344941bcf36b0d	True	0	attached
GROUPS	sg-0ce38b4da3483987a	launch-wizard-25
PRIVATEIPADDRESSES	True	ip-172-31-15-39.eu-central-1.compute.internal	172.31.15.39
ASSOCIATION	amazon	ec2-18-159-254-72.eu-central-1.compute.amazonaws.com	18.159.254.72
PLACEMENT	eu-central-1c		default
SECURITYGROUPS	sg-0ce38b4da3483987a	launch-wizard-25
STATE	16	running
TAGS	Name	d040949-tmp-gardenlinux177
```

some network issue gcp/azure testing onging

**Comment by neo-liang-sap** [comment]
https://github.com/gardener/gardenctl/pull/390 is already merged and released in v0.23.0, if you would like to revert https://github.com/gardener/gardenctl/pull/390 please include the revert code in this PR, thanks

**Comment by tedteng** [comment]
The hotfix #390  break AWS/GCP/AZ SSH feature https://github.com/gardener/gardenctl/issues/394

PR to fix SSH and subcommand aws/gcp/az https://github.com/gardener/gardenctl/pull/391

**Comment by tedteng** [comment]
for short summary, PR #391 will fix all the issues except the new issue I found https://github.com/gardener/gardenctl/issues/396 (v21)

I haven't found the suitable case to achieve the automation test for aws.go gcp.go az.go yet. That why the PR with [WIP], but The PR ready merge to fix most of the issues.  that depend on decided from @gardenctl-maintainers
