### ISSUE TITLE
gcloud subcommand error - An account is required when using .p12 keys

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#396]
**Describe the bug**
gcloud cli subcommand error 

**To Reproduce**
./gardenctl-darwin-amd64 gcloud compute instances list
ERROR: (gcloud.auth.activate-service-account) Missing required argument [ACCOUNT]: An account is required when using .p12 keys
![image](https://user-images.githubusercontent.com/42234376/96413127-c39b0480-121d-11eb-9d9a-f976b29ae974.png)

**Expected behavior**

**Screenshots**

**Gardenctl Version (please complete the following information):**
 The version I check is v21 so at least the issue exist start from v21
gardenctl:
		version     : v0.21.0
		build date  : 2020-08-23
		go version  : go1.14.6
		go compiler : gc
		platform    : darwin/amd64

**Additional context**

**Comment by neo-liang-sap** [comment]
/assign

Hi @tedteng , could you please share which cluster you are testing with? i randomly picked two gcp clusters but seems ok

![image](https://user-images.githubusercontent.com/42594392/96423042-627a2d80-122b-11eb-9845-3b0960bf5e6e.png)
![image](https://user-images.githubusercontent.com/42594392/96423076-6d34c280-122b-11eb-8fb4-0f97eaff25f6.png)

Thanks!
-Neo

**Comment by tedteng** [comment]
I got the same error even ` gardenctl gcloud -- -v`, It maybe my local env issue. will take a look today.

**Comment by dansible** [comment]
closing as local issue
