### ISSUE TITLE
Add landscape information

### ISSUE THREAD

**Issue by DockToFuture** [gardener/gardenctl#41]
Add a cmd to expose landscape information via a garden cluster.
- total number of shoots per garden cluster
- number of shoots per iaas in a garden cluster

Expose further landscape information (obligatory):

- number of nodes
- number of cpus etc.

**Comment by vlerenc** [comment]
This data (and much more) is already available at the gardener metrics endpoint. You could query that instead? If you are interested, please approach @dkistner and @wyb1.

**Comment by DockToFuture** [comment]
Yes, the gardener metrics endpoint will be integrated in the future.
