### ISSUE TITLE
If the seed resource is missing the secretRef block to point to the seed access credentials, gardenctl panic errors when trying to target seed

### ISSUE THREAD

**Issue by wwatson13** [gardener/gardenctl#411]
**Describe the bug**
When creating an external seed, the instructions did not specify to include the block secretRef in the spec for the seed or create the appropiate seed secret. This does not create any issues with the operation of the seed, however it impacts the ability of to use gardenctl to target the seed.  Gardenctl does not properly handle the error of the missing secret reference or the missing seed and should be updated to properly detect the condition.

Overall the condition I believe should not exist when creating external seeds, but regardless gardenctl should be able to properly handle the condition and report the issue.

The expected format of the spec section of the seed resource  is below, to recreate the issue, remove secretRef, and then try to target the designated seed.
"spec": {
			"backup": {
				...
				}
			},
			"dns": {
				...
			},
			"networks": {
				...
			},
			"provider": {
				...
			},
			"secretRef": {
				"name": "seed-us-gov-west-1",
				"namespace": "garden"
			},
			"settings": {
				...
			}
		}

**To Reproduce**
Within a seed resource, edit to remove the spec.secretRef block

1. Which target was set 'gardenctl get target'. gardenctl get target -g <garden> -s <seed>
2. Which command was entered [e.g. 'gardenctl show vpn-seed'] gardenctl get target -g <garden> -s <seed>
3. What was the output of the command 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1e4dd46]

goroutine 1 [running]:
github.com/gardener/gardenctl/pkg/cmd.targetSeed(0x22f2260, 0x2ddf120, 0x22f2280, 0x2ddf120, 0xc0002ef240, 0x1a, 0x1)
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/target.go:452 +0x1f6
github.com/gardener/gardenctl/pkg/cmd.seedWrapper(0x22f2260, 0x2ddf120, 0x22f2280, 0x2ddf120, 0x22f2200, 0x2ddf120, 0x22f3760, 0xc0000be000, 0x22f3780, 0xc0000be008, ...)
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/target.go:989 +0x29c
github.com/gardener/gardenctl/pkg/cmd.NewTargetCmd.func1(0xc0002e6000, 0xc000263300, 0x0, 0x4, 0x0, 0x0)
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/target.go:86 +0x5da
github.com/spf13/cobra.(*Command).execute(0xc0002e6000, 0xc000263240, 0x4, 0x4, 0xc0002e6000, 0xc000263240)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2da4140, 0x1d, 0xc0000bdc40, 0x36)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/d068290/go/src/github.com/gardener/gardenctl/vendor/github.com/spf13/cobra/command.go:864
github.com/gardener/gardenctl/pkg/cmd.Execute()
	/Users/d068290/go/src/github.com/gardener/gardenctl/pkg/cmd/root.go:111 +0x3aa
main.main()
	/Users/d068290/go/src/github.com/gardener/gardenctl/cmd/gardenctl/main.go:20 +0x20

**Expected behavior**
gardenctl should report an error that it is unable to target seed due to missing information.

**Screenshots**

**Gardenctl Version (please complete the following information): v0.19.0 and v0.21.0
 - Version/Commit [e.g. b21b4bde14663faee381697cb1d93a8b53a3e81a]

**Additional context**

**Comment by neo-liang-sap** [comment]
Hi @wwatson13 , could you please provide more details:
- which garden you are targeting
- which seed you are targeting
- after targeting the seed, what command line you run and met the problem

**Comment by petersutter** [comment]
@tedteng: With the introduction of the [gardenlet](https://github.com/gardener/gardener/releases/tag/v0.33.0) the `spec.secretRef` is optional on the seed resource.

In case a shoot is used as seed, the flag `with-secret-ref` has to be added to the `shoot.gardener.cloud/use-as-seed` annotation so that the `spec.secretRef` is set on the seed.

**Comment by neo-liang-sap** [comment]
> @tedteng: With the introduction of the [gardenlet](https://github.com/gardener/gardener/releases/tag/v0.33.0) the `spec.secretRef` is optional on the seed resource.
> 
> In case a shoot is used as seed, the flag `with-secret-ref` has to be added to the `shoot.gardener.cloud/use-as-seed` annotation so that the `spec.secretRef` is set on the seed.

Hi @petersutter i guess you were about to mentioning me :) Chinese names looks alike ;)
Thanks for explanation, i will modify code to make `spec.secretRef` to be optional

**Comment by petersutter** [comment]
whoops, I was answering from the phone and got things mixed up, sorry @neo-liang-sap :)

> One question, in scenario `spec.secretRef` is not present in a seed, where can i get the `kubeconfig` for this seed? i'm asking this as we need `spec.secretRef` to extract `kubeSecret.Data["kubeconfig"]` which is seed kubeconfig content

I don't think you will be able to access such seeds if the `secretRef` is missing. If it should be accessible, the operator has to either set the `spec.secretRef` on the `Seed` and provide the secret or add the flag to the annotation as written above in case it's a shoot.

cc @rfranzke anything I missed?

**Comment by neo-liang-sap** [comment]
Ah thanks @petersutter @rfranzke for explanation, then i will add some logic to check when `spec.secretRef` is unavailable, gardenctl will exit and error msg like "the seed is inaccessiable xxxxx"... thanks for explanation!
-Neo

**Comment by wwatson13** [comment]
Sorry, missed the earlier question.  This is for NS2 gardener environments and we have a number of seeds that are not Shooted Seeds.  I can not provide access to the gardens as they are controlled.  However the scenario should be easy to recreate.

**Comment by neo-liang-sap** [comment]
PR - https://github.com/gardener/gardenctl/pull/451
