### ISSUE TITLE
remove KubernetesDashboard from logs.go

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#414]
**Describe the bug**
found KubernetesDshboard no long exist from UI and `kube-system`

![image](https://user-images.githubusercontent.com/42234376/97383784-55cf9680-1909-11eb-9c8d-5af452a989b8.png)

https://github.com/gardener/gardenctl/blob/f14cfa407aceea27d9d8a9579c5532e245a8e455/pkg/cmd/logs.go#L426-L461

**To Reproduce**
1. Which target was set 'gardenctl get target'
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
3. What was the output of the command 

**Expected behavior**

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - Version/Commit [e.g. b21b4bde14663faee381697cb1d93a8b53a3e81a]

**Additional context**

**Comment by petersutter** [comment]
The kubernetes dashboard is an addon. Most likely this addon is not enabled on your cluster

**Comment by tedteng** [comment]
Thanks for the information and /close it
