### ISSUE TITLE
setup grafana dashboard and submit gardenctl version on execution

### ISSUE THREAD

**Issue by andrei-panov** [gardener/gardenctl#415]
It might give us some insights if we start collecting information about gardenctl usage in terms of version number.

Like it happened recently with releasing the broken version it was not clear how urgent we should release a bugfix or it's fine to wait until the next release.

**Comment by petersutter** [comment]
One can still go back to a previous released `gardenctl` version if it's super urgent. The problem should be tracked in an issue of course.
I would vote against such a central tracking feature for this open source component

**Comment by andrei-panov** [comment]
closed since looks not relevant
