### ISSUE TITLE
Logs for controlplane components should not require a shoot to be targeted

### ISSUE THREAD

**Issue by dansible** [gardener/gardenctl#436]
When getting logs for the apiserver, etcd, and other control plane components, `gardenctl` requires you to have a shoot targeted. If users are already targeting the controlplane, it should be possible to get logs for anything running on the seed without needing to target a shoot

List of logging components on the seed:
- ~~gardener-controller-manager~~ existing logic doesn't require shoot to be targeted for gardener-controller-manager
- ~~kube-apiserver~~ done
- ~~kube-scheduler~~ done
- ~~kube-controller-manager~~ done
- ~~etcd-main~~ done
- ~~etcd-events~~ done
- ~~vpn-seed~~ done
- ~~machine-controller-manager~~ done
- ~~prometheus~~ done
- ~~gardenlet~~ done
- ~~cluster-autoscaler~~ done
- ~~tf~~

**Comment by neo-liang-sap** [comment]
will work on this one after https://github.com/gardener/gardenctl/pull/437 close

**Comment by neo-liang-sap** [comment]
tf issue fixed in comments https://github.com/gardener/gardenctl/issues/470
