### ISSUE TITLE
implement `gardenctl wakeup` to wake up a shoot cluster and `gardenctl hibernate` to hibernate a shoot cluster after shoot targeted

### ISSUE THREAD

**Issue by neo-liang-sap** [gardener/gardenctl#450]
as titled.
After shoot is targeted,

If the shoot is hibernated, `gardenctl wakeup` will wakeup the shoot, wait until shoot waked up.
If the shoot is not hibernated, print out msg indicating the shoot status.

If the shoot is not hibernated, `gardenctl hibernate` will hibernate the shoot, wait until shoot hibernated.
If the shoot is hibernated, print out msg indicating the shoot status.
/assign

**Comment by anoopjb** [comment]
IMHO, This gardenctl feature will be useful. 👍 

In our Jenkins CI runs we need to wake the cluster when the build starts and hibernate when the job finishes.
Now we are planning to use `kubectl patch shoot` to set `/spec/hibernation/enabled` and achieve hibernation. We feel this approach will break at some point when there is a change in the shoot CRD.
It will be nice to have this support from gardenctl.

**Comment by neo-liang-sap** [comment]
i will work on this issue when available
/reopen
