### ISSUE TITLE
PR conflicts not watched 

### ISSUE THREAD

**Issue by tedteng** [gardener/gardenctl#452]
**Describe the bug**
The PRs may affected by one PR merged.  however, the conflict msg never notice the owner either mail or github comment.

I want to use an action to watch the PR conflict and mention the owner in the comment when conflict occurs. 

![image](https://user-images.githubusercontent.com/42234376/99473253-2e5a6f80-2985-11eb-8088-69165d066eb7.png)

**Comment by tedteng** [comment]
before meger conflict PR
![image](https://user-images.githubusercontent.com/42234376/99494947-d172af80-29ac-11eb-9155-8860581ce701.png)

conflict check - remove all labels and tag `PR: need rebase`
![image](https://user-images.githubusercontent.com/42234376/99494967-dafc1780-29ac-11eb-9b2d-c1d56cc38e3a.png)

also email notify 
![image](https://user-images.githubusercontent.com/42234376/99495027-f5ce8c00-29ac-11eb-99e9-dd1371b3d3eb.png)

more details form PR , and conflict resolved

![image](https://user-images.githubusercontent.com/42234376/99495091-0bdc4c80-29ad-11eb-852a-05fbfd6a4f19.png)

email notify after conflict resolved
![image](https://user-images.githubusercontent.com/42234376/99495115-1d255900-29ad-11eb-835f-4fa44450a593.png)

**Comment by tedteng** [comment]
@dansible  currently I had achieved conflict detected and notify code owner by action and the test result looks well from my personal github repo.

during the research, I also achieved the auto-approved action before merge PR.  when numbers of `lgtm` comment reaches require times from the dedicated group person. the status becomes to approve. 

The next steps, I am planning to look for auto-merge after approval.  let me know whether we need this kind of feature in github.

**Comment by dansible** [comment]
Very nice, Ted. For the auto-merge after approval, I would hold off on that feature. I think the merging should be a deliberate action taken by the person who created the PR once it is approved, rather than an automated process as it gives people the opportunity to revise and make changes in case something is missed

**Comment by tedteng** [comment]
> Very nice, Ted. For the auto-merge after approval, I would hold off on that feature. I think the merging should be a deliberate action taken by the person who created the PR once it is approved, rather than an automated process as it gives people the opportunity to revise and make changes in case something is missed

Thanks, I will not implement the auto-merge feature.

**Comment by tedteng** [comment]
add the auto-approve feature.
