### ISSUE TITLE
Condense commands in `gardenctl infra orphan list`

### ISSUE THREAD

**Issue by dansible** [gardener/gardenctl#475]
Currently the `gardenctl infra orphan list` command doesn't provide any info on what the `gardenctl infra orphan list` command does. It would be great to:

- [ ] Condense the command into a single verb `gardenctl orphan`
- [ ] Add a meaningful help message for what this does (lists shoot resources that don't exist in the Gardener TF state)

**Comment by vlerenc** [comment]
@dansible @neo-liang-sap @DockToFuture I must admit, I didn't even know we have this command. What is it doing and how?

On the one hand, it seems it would have to have some knowledge on what and how Gardener creates the resources (to find orphans) and on the other hand, it's rather infrastructure-specific, which brings me to the point of extensibility in `gardenctl`.

Somewhat related, @rfranzke recently proposed to pull out all resources from the Terraform file. We already pull some out to hand them over to other components (such as the VPC ID), but not yet all.

**Comment by jfortin-sap** [comment]
@vlerenc Essentially, this command simply pulls the list of cloud resource ids from the cloud cli of the cloud provider associated to the shoot that should be present in the terraform state file, checks the presence in the terraform state file and if not it is declared an orphan.

**Comment by vlerenc** [comment]
@jfortin-sap It is a good approach, I guess. Then again, extensions don't have to use Terraform and what is not in the state file is not shown (could be identified via tags?).

In general, we have seen that this question is an interessant one to answer/show the information also to our end users (not only `gardenctl` users when doing ops). They ask us, which resources are you creating, what is blocking my operation, which permissions to you need/services do you use.
