### ISSUE TITLE
Support `hermesctl` CLI

### ISSUE THREAD

**Issue by dguendisch** [gardener/gardenctl#478]
When debugging ccloud issues, we sometimes use `openstack` to analyze resources in the customers accounts.
However sometimes it's necessary to check the auditlogs as well. CCloud colleagues have a CLI for this called `hermesctl`, see https://github.com/sapcc/hermes-ctl
We'd need support from gardenctl to execute `hermesctl` also for openstack clusters.

**Comment by neo-liang-sap** [comment]
Hi @dguendisch ,
thanks for this enhancement request, i would like to help on this issue.
I wonder what env variable needs to be set before using `hermes-ctl`? for example when running sth like `gardenctl openstack xxx` we exported list of env variable like `OS_AUTH_URL` `OS_TENANT_NAME` `OS_PROJECT_DOMAIN_NAME` etc , my assumption is `hermes-ctl` use same env variable as `openstack`?

I see from https://github.com/sapcc/hermes-ctl/blob/master/vendor/github.com/gophercloud/gophercloud/auth_options.go#L15-L20 , basically hermes-ctl use `OS_AUTH_URL` / `OS_USERNAME` / `OS_PASSWORD` / `OS_TENANT_NAME`, so these 4 env vars are at least needed to enable `gardenctl hermesctl`, my understanding correct?
Thanks.
-Neo

**Comment by dguendisch** [comment]
When I manually used `hermesctl` I just passed `OS_AUTH_URL` and `OS_AUTH_TOKEN`
But maybe @kayrus knows best whether `hermesctl` will work equally well with the env vars mentioned by you.

**Comment by neo-liang-sap** [comment]
`OS_AUTH_TOKEN` might be not feasible as i didn't find it in `secret->cloudprovider` or `CloudProfileConfig`.
I would prefer to use `OS_AUTH_URL`/ `OS_USERNAME`/ `OS_PASSWORD` / `OS_TENANT_NAME` / `OS_DOMAIN_NAME`
These values could be get from secret / CloudProfileConfig

**Comment by dguendisch** [comment]
I just tried with the above envs and got:
```
hermesctl list --target-id 0cfe3c17-46b5-4071-b07a-94242b493693
Error: Failed to list the events: Failed to list events: Request forbidden: [GET https://hermes.eu-nl-1.cloud.sap/v1/events?limit=10000&target_id=0cfe3c17-46b5-4071-b07a-94242b493693], error message: Forbidden
```

Did not think about this. Obviously our technical users don't necessarily have the audit permissions required to view the audit logs. Thus the same will be true for customer accounts.
Guess then it's not feasible/meaningful to add this in `gardenctl` 🤔
