### ISSUE TITLE
gardenctl get shoot leaks Seed's kubeconfig

### ISSUE THREAD

**Issue by timebertt** [gardener/gardenctl#486]
**Describe the bug**

When executing `gardenctl get shoot`, it leaks the Seed's kubeconfig in the current working directory.

**To Reproduce**

```
$ ls -l
total 0

$ g target -g some-garden -p foo -t bar
Garden:
KUBECONFIG=/Users/me/.kube/configs/some-garden/kubeconfig.yaml
Shoot:
KUBECONFIG=/Users/me/.garden/cache/some-garden/projects/foo/bar/kubeconfig.yaml

$ g get shoot
  ...
  apiVersion: v1
  kind: Config
  current-context: shoot--foo--bar
  ...

$ ls -l
total 8
-rw-r--r-- 1 d067603 5628 Dec  8 15:07 kubeconfig.yaml

$ cat kubeconfig.yaml
---
apiVersion: v1
kind: Config
current-context: shoot--garden--some-seed-cluster
...

```

**Expected behavior**

gardenctl should not leak any kubeconfigs in unexpected places.

**Gardenctl Version (please complete the following information):**
 - Version/Commit v0.24.0

**Comment by tedteng** [comment]
Thanks, just saw this leak issue too when `gardenctl get garden` will download kubeconfig as well, not sure whether design as this behavior
