### ISSUE TITLE
Can't shell into a node since my username contains uppercase letters

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardenctl#514]
**Describe the bug**
I tried to shell into a node, and got:
```
$ g shell ip-10-52-75-125.eu-central-1.compute.internal
Error: Pod "rootpod-I500152-10.52.75.125" is invalid: metadata.name: Invalid value: "rootpod-I500152-10.52.75.125": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Obviously this is because my username (I500152) contains an uppercase letter. 

**To Reproduce**
Always reproducible if your username contains uppercase letters.

**Expected behavior**
I should have been able to shell, my username should have been converted to lowercase when composing the rootpod name.

**Screenshots**

**Gardenctl Version (please complete the following information):**
```
gardenctl:
		version     : v0.24.1
		build date  : 2020-12-09
		go version  : go1.14.12
		go compiler : gc
		platform    : darwin/amd64
```

**Additional context**

**Comment by neo-liang-sap** [comment]
@stoyanr - could you please share your `gardenctl get target` for me to reproduce this issue? if it's confidential feel free send me via email or slack, thanks!
/assign
