### ISSUE TITLE
Adapt gardenctl to work with a virtual garden cluster

### ISSUE THREAD

**Issue by DockToFuture** [gardener/gardenctl#53]
Gardenctl should look for a virtual garden cluster apiserver in the ```garden``` namespace if available and use it.

**Comment by vlerenc** [comment]
Thanks, isn't that already resolved?

**Comment by DockToFuture** [comment]
If you have targeted a virtual garden cluster "sure" but it if you have targeted a soil cluster not all commands are actually supported, like ls shoots e.g..

**Comment by neo-liang-sap** [comment]
/close
close per discussion
