### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by mwieczorek** [gardener/gardenctl#55]
**Describe the bug**
I'd like to be able to connect to gardener cluster installed on GKE. Right now it's not possible because of such error when I do `gardenctl ls projects`:

`No Auth Provider found for name "gcp"`

**To Reproduce**
- install gardener on GKE
- get kubeconfig for GKE cluster, set proper `~/.garden/config` etc
- run `gardenctl ls projects`

**Expected behavior**
I will see list of projects

**Screenshots**

**Gardenctl Version (please complete the following information):**
 - 0.5.0

**Additional context**

**Comment by bergerx** [comment]
There had been a similar issue for Azure here: https://github.com/gardener/gardenctl/issues/33

**Comment by mwieczorek** [comment]
To fix it we need to just add:

```
_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
```

in one of the files. It also requires some additional projects/packages in Gopkg but the binary size is not much bigger

Would you consider such change?

**Comment by vasu1124** [comment]
@DockToFuture PTAL

**Comment by DockToFuture** [comment]
Gardenctl was updated to version 0.6.0, which contains your fix and also adds the azure packet.
