### ISSUE TITLE
No help if config is missing

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardenctl#6]
When not having a `config`, `gardenctl` is not helping the user, even `gardenctl -h` is not reachable, either:
```
$ gardenctl
open /Users/d043832/.garden/config: no such file or directory
$ gardenctl --help
open /Users/d043832/.garden/config: no such file or directory
```
Expected is to get to the help independent of the configuration file, ideally explaining what to do (without reading the README.md, that is not available locally if the user has not cloned the repo).

**Comment by DockToFuture** [comment]
Thank you for your Feedback. Link to URL was added in help page together with relevant informations.

**Comment by vpnachev** [comment]
If `$HOME/.garden/taget` is missing, then `gardenctl --help` returns an error `Please provide a gardenctl configuration before usage`

If I create an empty target file `touch $HOME/.garden/target`, then `gardenctl --help` is working fine.

**Comment by DockToFuture** [comment]
Thank you for pointing that out, it is fixed now.
