### ISSUE TITLE
gardenctl should not rely on installed jq

### ISSUE THREAD

**Issue by PlamenPanev** [gardener/gardenctl#74]
**Describe the bug**
gardenctl ssh does not work when `jq` is not installed.

**To Reproduce**
1. Which target was set 'gardenctl get target'
2. Which command was entered [e.g. 'gardenctl show vpn-seed']
```
$ gardenctl ssh <ip>
Downloaded id_rsa key
exit status 127
```
3. What was the output of the command 

**Expected behavior**

**Screenshots**

**Gardenctl Version (please complete the following information):**
```
$ gardenctl version
gardenctl:
	version     : 0.9.0
	build date  : 2019-03-22
	go version  : go1.12
	go compiler : gc
	platform    : darwin/amd64
```

**Additional context**
gardenctl should not rely on jq to be installed but should perform the logic with https://godoc.org/gopkg.in/yaml.v2 .

/cc @ialidzhikov

**Comment by jfortin-sap** [comment]
@DockToFuture Does this still need attention? I would like to pick it up.

**Comment by DockToFuture** [comment]
Yes, the issue is still open if you want to pick it up, I can assign it to you.

**Comment by jfortin-sap** [comment]
@DockToFuture great, assign it to me
