### ISSUE TITLE
Wrong response when dropping a project target

### ISSUE THREAD

**Issue by vlerenc** [gardener/gardenctl#9]
When dropping a project, the response is surprising/wrong ("A seed is targetted", even though it never was and the resulting target is only a Garden cluster):
```
$ gardenctl get target
target:
- kind: garden
  name: dev
- kind: project
  name: garden-core

$ gardenctl drop project
A seed is targeted

$ gardenctl get target
target:
- kind: garden
  name: dev
```

**Comment by DockToFuture** [comment]
First of all, thanks for reporting the Issue. I´ve looked into it, but I couldn´t reproduce the error. 

$ gardenctl get target
target:
- kind: garden
  name: dev
- kind: project
  name: garden-core

$ gardenctl drop project
Dropped project garden-core

$ gardenctl get target
target:
- kind: garden
  name: dev

**Comment by DockToFuture** [comment]
The issue is closed for now, when it reoccurs we can open it again. But it seems so far, that nobody else had the issue.
